package com.cs.core.config.strategy.usecase.migration;

import com.cs.core.config.strategy.configuration.base.IStrategy;
import com.cs.core.runtime.interactor.model.configuration.IIdsListParameterModel;
import com.cs.core.runtime.interactor.model.configuration.IVoidModel;

public interface IMigrationToRemoveAutoGeneratedAttributeFromDBStrategy extends IStrategy<IVoidModel, IIdsListParameterModel>{
  
}
