package com.cs.core.runtime.interactor.constants.projectspecific;

import java.util.HashMap;

import org.springframework.stereotype.Component;

import com.cs.constants.SystemLevelIds;
import com.cs.core.runtime.interactor.constants.application.Constants;

@Component
public class InitializeDataLabels__de_DE extends InitializeDataLabelKeys {
  
  public InitializeDataLabels__de_DE()
  {
    
    ASSET_COVERFLOW_ATTRIBUTE_LABEL = "File Preview__de_DE";
    ADDRESS_ATTRIBUTE_LABEL = "Address__de_DE";
    DESCRIPTION_ATTRIBUTE_LABEL = "Description__de_DE";
    DUE_DATE_ATTRIBUTE_LABEL = "Due Date__de_DE";
    FIRST_NAME_ATTRIBUTE_LABEL = "First Name__de_DE";
    LIST_PRICE_ATTRIBUTE_LABEL = "List Price__de_DE";
    LONG_DESCRIPTION_ATTRIBUTE_LABEL = "Long Description__de_DE";
    MINIMUM_PRICE_ATTRIBUTE_LABEL = "Minimum Price__de_DE";
    PID_ATTRIBUTE_LABEL = "PID__de_DE";
    PIN_CODE_ATTRIBUTE_LABEL = "Pin Code__de_DE";
    SELLING_PRICE_ATTRIBUTE_LABEL = "Selling Price__de_DE";
    SHORT_DESCRIPTION_ATTRIBUTE_LABEL = "Short Description__de_DE";
    SKU_ATTRIBUTE_LABEL = "SKU__de_DE";
    TELEPHONE_NUMBER_ATTRIBUTE_LABEL = "Telephone Number__de_DE";
    DISCOUNT_ATTRIBUTE_LABEL = "Discount (%)__de_DE";
    GTIN_ATTRIBUTE_LABEL = "GTIN__de_DE";
    LAST_NAME_ATTRIBUTE_LABEL = "Last Name__de_DE";
    MAXIMUM_PRICE_ATTRIBUTE_LABEL = "Maximum Price__de_DE";
    
    CREATED_BY_ATTRIBUTE = "Created By__de_DE";
    CREATED_ON_ATTRIBUTE = "Created On__de_DE";
    LAST_MODIFIED_ATTRIBUTE = "Last Modified__de_DE";
    LAST_MODIFIED_BY_ATTRIBUTE = "Last Modified By__de_DE";
    NAME_ATTRIBUTE = "Name__de_DE";
    
    DTP_ERROR_MARGIN_LABEL = "Error margin__de_DE";
    DTP_MAX_NO_OF_SLOTS_ATTRIBUTE_LABEL = "Maximum Number of Slots__de_DE";
    DTP_MINIMUM_SLOT_HEIGHT_ATTRIBUTE_LABEL = "Minimum Slot Height__de_DE";
    DTP_MINIMUM_SLOT_WIDTH_ATTRIBUTE_LABEL = "Minimum Slot Width__de_DE";
    DTP_DELTA_ATTRIBUTE_LABEL = "Delta__de_DE";
    
    I_META_FILE_NAME = "I_META_FILE_NAME__de_DE";
    I_META_DOCUMENT_TYPE = "I_META_DOCUMENT_TYPE__de_DE";
    I_APPLICATION = "I_APPLICATION__de_DE";
    I_CREATE_DATE = "I_CREATE_DATE__de_DE";
    I_MODIFICATION_DATE = "I_MODIFICATION_DATE__de_DE";
    I_META_FILE_SIZE = "I_META_FILE_SIZE__de_DE";
    I_DIMENSIONS = "I_DIMENSIONS__de_DE";
    I_DIMENSION_IN_INCH = "I_DIMENSION_IN_INCH__de_DE";
    I_RESOLUTION = "I_RESOLUTION__de_DE";
    I_BIT_DEPTH = "I_BIT_DEPTH__de_DE";
    I_COLOR_MODE = "I_COLOR_MODE__de_DE";
    I_COLOR_PROFILE = "I_COLOR_PROFILE__de_DE";
    I_META_CREATOR_AUTHOR = "I_META_CREATOR_AUTHOR__de_DE";
    I_META_CREATOR_STREET = "I_META_CREATOR_STREET__de_DE";
    I_META_CREATOR_LOCATION = "I_META_CREATOR_LOCATION__de_DE";
    I_META_CREATOR_STATE = "I_META_CREATOR_STATE__de_DE";
    I_META_CREATOR_POSTAL_CODE = "I_META_CREATOR_POSTAL_CODE__de_DE";
    I_META_CREATOR_COUNTRY = "I_META_CREATOR_COUNTRY__de_DE";
    I_META_CREATOR_TEL = "I_META_CREATOR_TEL__de_DE";
    I_META_CREATOR_EMAIL = "I_META_CREATOR_EMAIL__de_DE";
    I_META_CREATOR_WWW = "I_META_CREATOR_WWW__de_DE";
    I_META_HEADING = "I_META_HEADING__de_DE";
    I_META_DESCRIPTION = "I_META_DESCRIPTION__de_DE";
    I_META_KEYWORDS = "I_META_KEYWORDS__de_DE";
    I_META_LOCATION_DETAIL = "I_META_LOCATION_DETAIL__de_DE";
    I_META_LOCATION = "I_META_LOCATION__de_DE";
    I_META_STATE = "I_META_STATE__de_DE";
    I_META_COUNTRY = "I_META_COUNTRY__de_DE";
    I_META_TITEL = "I_META_TITEL__de_DE";
    I_META_COPYRIGHT = "I_META_COPYRIGHT__de_DE__de_DE";
    I_META_COPYRIGHT_STATUS = "I_META_COPYRIGHT_STATUS__de_DE";
    I_META_EXPOSURE_INDEX = "I_META_EXPOSURE_INDEX__de_DE";
    I_META_FOCAL_RANGE = "I_META_FOCAL_RANGE__de_DE";
    I_META_MAX_BLINDING_VALUE = "I_META_MAX_BLINDING_VALUE__de_DE";
    I_META_RECORDING_DATE = "I_META_RECORDING_DATE__de_DE";
    I_META_EXPOSURE_CONTROLS = "I_META_EXPOSURE_CONTROLS__de_DE";
    I_META_LIGHT_SOURCE = "I_META_LIGHT_SOURCE__de_DE";
    I_META_SENSOR_TYPE = "I_META_SENSOR_TYPE__de_DE";
    I_META_BRAND = "I_META_BRAND__de_DE";
    I_META_MODELL = "I_META_MODELL__de_DE";
    I_META_SERIAL_NUMBER = "I_META_SERIAL_NUMBER__de_DE";
    I_META_PIXEL_X_DIMENSION = "I_META_PIXEL_X_DIMENSION__de_DE";
    I_META_PIXEL_Y_DIMENSION = "I_META_PIXEL_Y_DIMENSION__de_DE";
    I_META_HIGH_RESOLUTION = "I_META_HIGH_RESOLUTION__de_DE";
    I_META_WIDTH_RESOLUTION = "I_META_WIDTH_RESOLUTION__de_DE";
    I_META_X_RESOLUTION = "I_META_X_RESOLUTION__de_DE";
    I_META_Y_RESOLUTION = "I_META_Y_RESOLUTION__de_DE";
    
    // Tags
    IS_ORDER_TAG_LABEL = "isOrder__de_DE";
    IS_SALES_TAG_LABEL = "isSales__de_DE";
    IS_BASEUNIT_TAG_LABEL = "isBaseUnit__de_DE";
    
    LISTING_STATUS_TAG_LABEL = "Listungsstatus";
    LISTING_STATUS_CATLOG_LABEL = "Neu";
    LISTING_STATUS_IGNORED_LABEL = "Nicht relevant";
    LISTING_STATUS_REJECTED_LABEL = "Zurückgewiesen";
    LISTING_STATUS_ONBOARDING_POOL_LABEL = "In Vorbereitung";
    LISTING_STATUS_RECOMMENDED_LABEL = "Empfohlen";
    LISTING_STATUS_SHADOW_ASSORTMENT_LABEL = "Schattensortiment";
    LISTING_STATUS_LISTED_LABEL = "Freigegeben";
    LIFE_STATUS_TAG_LABEL = "Lebenszyklusstatus";
    LIFE_STATUS_INBOX_LABEL = "Neu";
    LIFE_STATUS_NO_INTEREST_LABEL = "Nicht relevant";
    LIFE_STATUS_PREPARATION_LABEL = "In Vorbereitung";
    LIFE_STATUS_ACTIVE_LABEL = "Aktiv";
    LIFE_STATUS_ACTIVE_BLOCKED_LABEL = "Blockiert";
    LIFE_STATUS_ACTIVE_BANNED_LABEL = "Gesperrt";
    LIFE_STATUS_RETIRED_LABEL = "Inaktiv";
    LIFE_STATUS_ARCHIVED_LABEL = "Archiviert";
    LIFE_STATUS_DELETED_LABEL = "Gelöscht";
    STATUS_TAG_LABEL = "Status__de_DE";
    ENRICHMENT_TAG_LABEL = "Enrichment__de_DE";
    QUALITY_CHECK_TAG_LABEL = "Quality Check__de_DE";
    TRANSLATION_TAG_LABEL = "Translation__de_DE";
    APPROVAL_TAG_LABEL = "Approval__de_DE";
    PRODUCTIVE_TAG_LABEL = "Productive__de_DE";
    BLOCKED_FROM_PLANNING_LABEL = "Blocked from planning__de_DE";
    AVAILABILITY_TAG_LABEL = "Availability__de_DE";
    ON_REQUEST_LABEL = "On Request__de_DE";
    ON_STOCK_LABEL = "On Stock__de_DE";
    REGULARLY_AVAILABLE_LABEL = "Regularly Available__de_DE";
    DROP_SHIPPING_LABEL = "Drop Shipping__de_DE";
    LANGUAGE_TAG_LABEL = "Language__de_DE";
    ENGLISH_LABEL = "Englisch";
    GERMAN_LABEL = "Deutsche";
    SPANISH_LABEL = "Spanisch";
    ITALIAN_LABEL = "Italian__de_DE";
    FRENCH_LABEL = "Französisch";
    PORTUGESE_LABEL = "Portugese__de_DE";
    SWEDISH_LABEL = "Swedish__de_DE";
    
    SUPPORTED_LANGUAGES = "SupportedLanguages__de_DE";
    
    LANGUAGE = "language__de_DE";
    EN = "en__de_DE";
    DE = "de__de_DE";
    FR = "fr__de_DE";
    ES = "es__de_DE";
    EN_US = "English (U.S)__de_DE";
    EN_UK = "English (U.K)__de_DE";
    DE_DE = "Deutsch__de_DE";
    FR_FR = "Fran�ais__de_DE";
    ES_ES = "Espa�ol__de_DE";
    
    DEFAULT_DATA_INTEGRATION_TAB = "DefaultDataIntegrationTab__de_DE";
    DEFAULT_DASHBOARD_TAB = "DefaultDashboardTab__de_DE";
    
    T_STATUS_SYSTEM_LABEL = "Status__de_DE";
    T_STATUS_SYSTEM_NEU_LABEL = "Neu__de_DE";
    T_STATUS_SYSTEM_INAKTIV_LABEL = "Inaktiv__de_DE";
    T_STATUS_SYSTEM_AKTIV_LABEL = "Aktiv__de_DE";
    T_STATUS_SYSTEM_ARCHIVIERT_LABEL = "Archiviert__de_DE";
    T_STATUS_SYSTEM_GELOESCHT_LABEL = "GelÃ¶scht__de_DE";
    T_STATUS_SYSTEM_PREPARE_LABEL = "Vorbereitung__de_DE";
    T_STATUS_SYSTEM_BLOCKED_LABEL = "Gesperrt__de_DE";
    T_STATUS_PROJECT_LABEL = "Projektstatus__de_DE";
    
    T_CAMPAIGN_GOALS_LABEL = "Goals__de_DE";
    T_GOALS_BRAND_PROMOTION_LABEL = "Brand Promotion__de_DE";
    T_GOALS_SEASONAL_PROMOTION_LABEL = "Seasonal Promotion__de_DE";
    T_GOALS_NEW_ARRIVALS_LABEL = "New Arrivals__de_DE";
    T_GOALS_PROMOTION_HIGH_MARGIN_LABEL = "Promotion of Higher Margin Products__de_DE";
    T_GOALS_INVENTORY_CLEARANCE_LABEL = "Inventory Clearance__de_DE";
    T_GOALS_LOYALTY_POINTS_LABEL = "Niche group promotion (Loyalty Points)__de_DE";
    T_GOALS_SPECIAL_TOPIC_LABEL = "Special topic promotion__de_DE";
    T_GOALS_ACQUIRE_NEW_CUSTOMERS_LABEL = "Acquire new customers__de_DE";
    T_GOALS_RETAIN_EXISTING_CUSTOMERS_LABEL = "Retain existing customers__de_DE";
    
    T_CAMP_TYPE_LABEL = "Kampagnen-Typ__de_DE";
    T_CAMP_TYPE_NATIONAL_LABEL = "National__de_DE";
    T_CAMP_TYPE_REGIONAL_LABEL = "Regional__de_DE";
    T_CAMP_TYPE_CATALINA_LABEL = "Catalina__de_DE";
    T_CAMP_TYPE_DCARD_LABEL = "DeutschlandCard__de_DE";
    T_CAMP_TYPE_LIEFERANT_LABEL = "Lieferant__de_DE";
    TASK_STATUS_TAG_LABEL = "Task-Status__de_DE";
    PLANNED_LABEL = "Planned__de_DE";
    READY_LABEL = "Ready__de_DE";
    DECLINED_LABEL = "Declined__de_DE";
    IN_PROGRESS_LABEL = "In_Progress__de_DE";
    DONE_LABEL = "Done__de_DE";
    VERIFIED_LABEL = "Verified__de_DE";
    SIGNED_OFF_LABEL = "Signed_Off__de_DE";
    
    RESOLUTION_TAG_LABEL = "AuflÃ¶sung";
    RESOLUTION_300P_LABEL = "300_dpi__de_DE";
    RESOLUTION_150P_LABEL = "150_dpi__de_DE";
    RESOLUTION_72P_LABEL = "72_dpi__de_DE";
    IMAGE_EXTENSION_LABEL = "Image Extension__de_DE";
    IMAGE_FORMAT_JPG_LABEL = "jpg__de_DE";
    IMAGE_FORMAT_PNG_LABEL = "png__de_DE";
    IMAGE_FORMAT_ORIGINAL_LABEL = "original__de_DE";
    
    T_STATUS_PROJEKT_VERWENDBAR = "Verwendbar";
    T_STATUS_PROJEKT_IN_PLANUNG = "In Planung";
    T_STATUS_PROJEKT_ABGESCHLOSSEN = "abgeschlossen";
    T_STATUS_PROJEKT_ZUR_UBERARBEITUNG = "zur Ãœberarbeitung";
    T_STATUS_PROJEKT_QUALITAT_SICHERN = "QualitÃ¤t sichern";
    T_STATUS_PROJEKT_FEHLER_BEARBEITEN = "Fehler bearbeiten";
    T_STATUS_PROJEKT_LIZENZ_FEHLT = "Lizenz fehlt";
    T_STATUS_PROJEKT_ABGEBROCHEN = "abgebrochen";
    
    CREATED_EVENT_LABEL = "Created__de_DE";
    
    LANGUAGE_TAXONOMY_LABEL = "Language__de_DE";
    
    PRICING_PROPERTY_COLLECTION_LABEL = "Pricing__de_DE";
    ARTICLE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "General Information__de_DE";
    MARKET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Market General Information__de_DE";
    ASSET_GENERAL_INFORMATION_PROPERTY_COLLETION_LABEL = "Asset Information__de_DE";
    CAMPAIGN_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "General Information__de_DE";
    PROMOTION_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Promotion General Information__de_DE";
    SUPPLIER_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Supplier General Information__de_DE";
    TEXTASSET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Text-Asset General Information__de_DE";
    DEFAULT_X_RAY_PROPERTY_COLLECTION_LABEL = "Default X-Ray Collection__de_DE";
    METADATA_COLLECTION_LABEL = "Metadata__de_DE";
    UNIT_DEFAULT_PROPERTYCOLLECTION_LABEL = "Unit Information__de_DE";
    DTP_TEMPLATE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Template General Information__de_DE";
    DTP_DOCUMENT_TEMPLATE_INFORMATION_PROPERTY_COLLECTION_LABEL = "Document Template Information__de_DE";
    DTP_TEMPLATE_FILE_INFOMATION_PROPERTY_COLLECTION_LABEL = "Template File Information__de_DE";
    
    STANDARD_ARTICLE_KLASS_LABEL = "Article__de_DE";
    STANDARD_SET_KLASS_LABEL = "Set__de_DE";
    STANDARD_COLLETION_KLASS_LABEL = "Collection__de_DE";
    STANDARD_CHANNEL_CLASSES_LABEL = "Channel Classes__de_DE";
    STANDARD_PRODUCT_TYPES_LABEL = "Product Types__de_DE";
    STANDARD_SINGLE_ARTICLE = "Single Article__de_DE";
    STANDARD_ATTRIBUTION_CLASSES_LABEL = "Attribution Classes__de_DE";
    STANDARD_FILE_KLASS_LABEL = "Datei";
    STANDARD_VERSION_KLASS_LABEL = "Version Class__de_DE";
    STANDARD_GOLDEN_ARTICLE_KLASS_LABEL = "Golden Article__de_DE";
    
    STANDARD_VIDEO_KLASS_LABEL = "Video__de_DE";
    STANDARD_DOCUMENT_KLASS_LABEL = "Document__de_DE";
    STANDARD_IMAGE_KLASS_LABEL = "Image__de_DE";
    STANDARD_ATTACHMENT_KLASS_LABEL = "Attachment__de_DE";
    STANDARD_ASSET_KLASS_LABEL = "Medien";
    STANDARD_SMARTDOCUMENT_KLASS_LABEL = "Smart Document__de_DE";
    
    STANDARD_CAMPAIGN_KLASS_LABEL = "Campaign__de_DE";
    
    STANDARD_PROPERTY_COLLECTION_TAB_LABEL = "Properties__de_DE";
    STANDARD_RELATIONSHIP_TAB_LABEL = "Relationships__de_DE";
    STANDARD_CONTEXT_TAB_LABEL = "Contexts__de_DE";
    STANDARD_TASK_TAB_LABEL = "Tasks__de_DE";
    STANDARD_TIMELINE_TAB_LABEL = "Timeline__de_DE";
    STANDARD_RENDITION_TAB_LABEL = "Renditions__de_DE";
    STANDARD_OVERVIEW_TAB_LABEL = "Overview__de_DE";
    STANDARD_MDM_TAB_LABEL = "Mdm__de_DE";
    
    PROMOTION_LABEL = "Promotion__de_DE";
    SUPPLIER_LABEL = "Supplier__de_DE";
    MARKET_LABEL = "Market__de_DE";
    
    MARKETING_PRODUCT_LABEL = "Marketing Product__de_DE";
    MARKETING_BUNDLE_LABEL = "Marketing Bundle__de_DE";
    
    STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL = "PublicationTemplate__de_DE";
    STANDARD_DTP_PUBLICATION_LABEL = "Publication__de_DE";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL = "Document Template__de_DE";
    STANDARD_DTP_PRODUCT_TEMPLATE_LABEL = "Product Template__de_DE";
    STANDARD_DTP_ABSTRACT_DOCUMENT_TEMPLATE_LABEL = "Abstract Document Template__de_DE";
    STANDARD_DTP_ABSTRACT_PRODUCT_TEMPLATE_LABEL = "Abstract Product Template__de_DE";
    STANDARD_DTP_ABSTRACT_PUBLICATION_TEMPLATE_LABEL = "Abstract Publication Template__de_DE";
    STANDARD_DTP_ABSTRACT_PUBLICATION_LABEL = "Abstract Publication__de_DE";
    
    STANDARD_DTP_ABSTRACT_DOCUMENT_LABEL = "Abstract Document__de_DE";
    STANDARD_DTP_DOCUMENT_LABEL = "Document__de_DE";
    STANDARD_DTP_DOCUMENT_VARIANT_LABEL = "Document Variant__de_DE";
    
    PROMOTION_LABEL = "Aktionen";
    SUPPLIER_LABEL = "Supplier__de_DE";
    MARKET_LABEL = "Target_de";
    
    STANDARD_ORGANIZATION = "Standard Organization__de_DE";
    
    ADMIN_LABEL = "admin__de_DE";
    
    STANDARD_SYSTEM = "Standard System__de_DE";
    
    SUPPLIERS_LABEL = "Lieferanten";
    MARKETPLACES_LABEL = "Marketplaces__de_DE";
    DISTRIBUTORS_LABEL = "Distributors__de_DE";
    WHOLESALERS_LABEL = "Wholesalers__de_DE";
    TRANSLATION_AGENCY_LABEL = "Translation Agency__de_DE";
    CONTENT_ENRICHMENT_AGENCY_LABEL = "Content Enrichment Agency__de_DE";
    DIGITAL_ASSET_AGENCY_LABEL = "Digital Asset Agency__de_DE";
    
    // Role
    RESPONSIBLE_ROLE_LABEL = "Responsible__de_DE";
    ACCOUNTABLE_ROLE_LABEL = "Accountable__de_DE";
    CONSULTED_ROLE_LABEL = "Consulted__de_DE";
    INFORMED_ROLE_LABEL = "Informed__de_DE";
    VERIFY_ROLE_LABEL = "Verify__de_DE";
    SIGNOFF_ROLE_LABEL = "Sign-off__de_DE";
    ADMIN_ROLE_LABEL = "Admin__de_DE";
    
    RACIVS_ROLE_LABELS = new String[] { RESPONSIBLE_ROLE_LABEL, ACCOUNTABLE_ROLE_LABEL,
        CONSULTED_ROLE_LABEL, INFORMED_ROLE_LABEL, VERIFY_ROLE_LABEL, SIGNOFF_ROLE_LABEL,
        ADMIN_ROLE_LABEL };
    
    APPROVER_ROLE_LABEL = "Approver(Sign-Off)__de_DE";
    OWNER_ROLE_LABEL = "Owner(Responsible)__de_DE";
    SUBSCRIBER_ROLE_LABEL = "Subscriber(Informed)__de_DE";
    CONTRIBUTOR_ROLE_LABEL = "Contributor(Consulted)__de_DE";
    REVIEWER_ROLE_LABEL = "Reviewer(Verify)__de_DE";
    SENIOR_MANAGER_ROLE_LABEL = "Senior Manager(Accountable)__de_DE";
    ASSIGNEE_ROLE_LABEL = "Assignee__de_DE";
    
    STANDARD_ARTICLE_ASSET_RELATIONSHIP_LABEL = "Article-Asset Relationship__de_DE";
    STANDARD_MARKET_ASSET_RELATIONSHIP_LABEL = "Market-Asset Relationship__de_DE";
    STANDARD_CAMPAIGN_ASSET_RELATIONSHIP_LABEL = "Campaign-Asset Relationship__de_DE";
    STANDARD_CAMPAIGN_CAMPAIGN_RELATIONSHIP_LABEL = "Campaign-Campaign Relationship__de_DE";
    STANDARD_TEXTASSET_ASSET_RELATIONSHIP_LABEL = "TextAsset-Asset Relationship__de_DE";
    STANDARD_SUPPLIER_ASSET_RELATIONSHIP_LABEL = "Supplier-Asset Relationship__de_DE";
    STANDARD_PROMOTION_ASSET_RELATIONSHIP_LABEL = "Promotion-Asset Relationship__de_DE";
    STANDARD_ARTICLE_MARKET_RELATIONSHIP_LABEL = "Artikel MÃ¤rkte__de_DE";
    STANDARD_ARTICLE_GOLDEN_ARTICLE_RELATIONSHIP_LABEL = "Article-GoldenArticle Relationship__de_DE";
    STANDARD_ARTICLE_MARKETING_ARTICLE_RELATIONSHIP_LABEL = "Article-MarketingArticle Relationship__de_DE";
    
    STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_LABEL = "Publication Template - Document Template Relationship__de_DE";
    STANDARD_DTP_DOCUMENT_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "DocumentTemplate - Asset Relationship__de_DE";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_ARTICLES_RELATIONSHIP_LABEL = "DocumentTemplate - Marketing Article Relationship__de_DE";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_PRODUCT_TEMPLATES_RELATIONSHIP_LABEL = "DocumentTemplate - Product Template Relationship__de_DE";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_BUNDLE_RELATIONSHIP_LABEL = "DocumentTemplate - Marketing Bundle Relationship__de_DE";
    
    STANDARD_DTP_DOCUMENT_TEMPLATE_PAGE_PREVIEW_RELATIONSHIP_LABEL = "DocumentTemplate - Page Preview Relationship__de_DE";
    STANDARD_DTP_PRODUCT_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "Product Template - Asset Relationship__de_DE";
    STANDARD_DTP_PUBLICATION_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "Publication Template - Asset Relationship__de_DE";
    STANDARD_DTP_PUBLICATION_DTP_PUBLICATION_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Publication Template__de_DE";
    STANDARD_DTP_PUBLICATION_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Document Template__de_DE";
    STANDARD_DTP_PUBLICATION_DTP_PRODUCT_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Product Template__de_DE";
    STANDARD_MARKETING_ARTICLE_ASSET_RELATIONSHIP_LABEL = "MarketingArticle - Asset Relationship__de_DE";
    STANDARD_MARKETING_BUNDLE_ASSET_RELATIONSHIP_LABEL = "MarketingBundle - Asset Relationship__de_DE";
    
    PAGE_PREVIEWS = "Page Previews__de_DE";
    
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_ARTICLES_RELATIONSHIP_LABEL = "Document Template - Marketing Article__de_DE";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_BUNDLES_RELATIONSHIP_LABEL = "Document Template - Marketing Bundle__de_DE";
    STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL = "Publication Template - Document Template__de_DE";
    
    // _LABEL = "side 1__de_DE" ;
    ARTICLES_LABEL = "Articles__de_DE";
    TARGETS_LABEL = "Targets__de_DE";
    CAMPAIGN_LABEL = "Campaign__de_DE";
    TEXTASSET_LABEL = "TextAsset__de_DE";
    SUPPLIER_LABEL = "Supplier__de_DE";
    PROMOTION_LABEL = "Promotion__de_DE";
    
    IMAGES = "Images__de_DE";
    
    STANDARD_OVERVIEW_TAB_LABEL = "overview_tab__de_DE";
    STANDARD_PROPERTY_COLLECTION_TAB_LABEL = "property_collection_tab__de_DE";
    STANDARD_RELATIONSHIP_TAB_LABEL = "relationship_tab__de_DE";
    STANDARD_CONTEXT_TAB_LABEL = "context_tab__de_DE";
    STANDARD_TASK_TAB_LABEL = "task_tab__de_DE";
    STANDARD_TIMELINE_TAB_LABEL = "timeline_tab__de_DE";
    STANDARD_RENDITION_TAB_LABEL = "renditions_tab__de_DE";
    STANDARD_CONFIGURATION_TAB_LABEL = "configurations_tab__de_DE";
    STANDARD_MDM_TAB_LABEL = "mdm_tab__de_DE";
    STANDARD_DUPLICATE_TAB_LABEL = "duplicates_tab__de_DE";
    
    STANDARD_TAB_LABELS = new String[] { STANDARD_OVERVIEW_TAB_LABEL,
        STANDARD_PROPERTY_COLLECTION_TAB_LABEL, STANDARD_RELATIONSHIP_TAB_LABEL,
        STANDARD_CONTEXT_TAB_LABEL, STANDARD_TASK_TAB_LABEL, 
        STANDARD_TIMELINE_TAB_LABEL, STANDARD_RENDITION_TAB_LABEL,
        STANDARD_CONFIGURATION_TAB_LABEL, STANDARD_MDM_TAB_LABEL, STANDARD_DUPLICATE_TAB_LABEL };
    
    DTP_KLASS_LABELS = new String[] { STANDARD_DTP_ABSTRACT_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_ABSTRACT_PRODUCT_TEMPLATE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, STANDARD_DTP_ABSTRACT_PUBLICATION_TEMPLATE_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL };
    
    DTP_PUBLICATION_LABELS = new String[] { STANDARD_DTP_ABSTRACT_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_LABEL };
    
    DTP_DOCUMENT_LABELS = new String[] { STANDARD_DTP_ABSTRACT_DOCUMENT_LABEL,
        STANDARD_DTP_DOCUMENT_LABEL, STANDARD_DTP_DOCUMENT_VARIANT_LABEL };
    
    ATTRIBUTE_LABELS = new String[] { ASSET_COVERFLOW_ATTRIBUTE_LABEL, ADDRESS_ATTRIBUTE_LABEL,
        DESCRIPTION_ATTRIBUTE_LABEL, DUE_DATE_ATTRIBUTE_LABEL, FIRST_NAME_ATTRIBUTE_LABEL,
        LIST_PRICE_ATTRIBUTE_LABEL, LONG_DESCRIPTION_ATTRIBUTE_LABEL, MINIMUM_PRICE_ATTRIBUTE_LABEL,
        PID_ATTRIBUTE_LABEL, PIN_CODE_ATTRIBUTE_LABEL, SELLING_PRICE_ATTRIBUTE_LABEL,
        SHORT_DESCRIPTION_ATTRIBUTE_LABEL, SKU_ATTRIBUTE_LABEL, TELEPHONE_NUMBER_ATTRIBUTE_LABEL,
        DISCOUNT_ATTRIBUTE_LABEL, GTIN_ATTRIBUTE_LABEL, LAST_NAME_ATTRIBUTE_LABEL,
        MAXIMUM_PRICE_ATTRIBUTE_LABEL, CREATED_BY_ATTRIBUTE, CREATED_ON_ATTRIBUTE,
        LAST_MODIFIED_ATTRIBUTE, LAST_MODIFIED_BY_ATTRIBUTE, NAME_ATTRIBUTE,
        DTP_MAX_NO_OF_SLOTS_ATTRIBUTE_LABEL, DTP_MINIMUM_SLOT_WIDTH_ATTRIBUTE_LABEL,
        DTP_MINIMUM_SLOT_HEIGHT_ATTRIBUTE_LABEL, DTP_ERROR_MARGIN_LABEL,
        DTP_DELTA_ATTRIBUTE_LABEL };
    
    METADATA_ATTRIBUTES_LABELS = new String[] { I_META_FILE_NAME, I_META_DOCUMENT_TYPE,
        I_APPLICATION, I_CREATE_DATE, I_MODIFICATION_DATE, I_META_FILE_SIZE, I_DIMENSIONS,
        I_DIMENSION_IN_INCH, I_RESOLUTION, I_BIT_DEPTH, I_COLOR_MODE, I_COLOR_PROFILE,
        I_META_CREATOR_AUTHOR, I_META_CREATOR_STREET, I_META_CREATOR_LOCATION, I_META_CREATOR_STATE,
        I_META_CREATOR_POSTAL_CODE, I_META_CREATOR_COUNTRY, I_META_CREATOR_TEL,
        I_META_CREATOR_EMAIL, I_META_CREATOR_WWW, I_META_HEADING, I_META_DESCRIPTION,
        I_META_KEYWORDS, I_META_LOCATION_DETAIL, I_META_LOCATION, I_META_STATE, I_META_COUNTRY,
        I_META_TITEL, I_META_COPYRIGHT, I_META_COPYRIGHT_STATUS, I_META_EXPOSURE_INDEX,
        I_META_FOCAL_RANGE, I_META_MAX_BLINDING_VALUE, I_META_RECORDING_DATE,
        I_META_EXPOSURE_CONTROLS, I_META_LIGHT_SOURCE, I_META_SENSOR_TYPE, I_META_BRAND,
        I_META_MODELL, I_META_SERIAL_NUMBER, I_META_PIXEL_X_DIMENSION, I_META_PIXEL_Y_DIMENSION,
        I_META_HIGH_RESOLUTION, I_META_WIDTH_RESOLUTION, I_META_X_RESOLUTION, I_META_Y_RESOLUTION };
    
    TAG_LABELS = new String[] { LISTING_STATUS_TAG_LABEL, LISTING_STATUS_CATLOG_LABEL,
        LISTING_STATUS_IGNORED_LABEL, LISTING_STATUS_REJECTED_LABEL,
        LISTING_STATUS_ONBOARDING_POOL_LABEL, LISTING_STATUS_RECOMMENDED_LABEL,
        LISTING_STATUS_SHADOW_ASSORTMENT_LABEL, LISTING_STATUS_LISTED_LABEL, LIFE_STATUS_TAG_LABEL,
        LIFE_STATUS_INBOX_LABEL, LIFE_STATUS_NO_INTEREST_LABEL, LIFE_STATUS_PREPARATION_LABEL,
        LIFE_STATUS_ACTIVE_LABEL, LIFE_STATUS_ACTIVE_BLOCKED_LABEL, LIFE_STATUS_ACTIVE_BANNED_LABEL,
        LIFE_STATUS_RETIRED_LABEL, LIFE_STATUS_ARCHIVED_LABEL, LIFE_STATUS_DELETED_LABEL,
        STATUS_TAG_LABEL, ENRICHMENT_TAG_LABEL, QUALITY_CHECK_TAG_LABEL, TRANSLATION_TAG_LABEL,
        APPROVAL_TAG_LABEL, PRODUCTIVE_TAG_LABEL, BLOCKED_FROM_PLANNING_LABEL,
        AVAILABILITY_TAG_LABEL, ON_REQUEST_LABEL, ON_STOCK_LABEL, REGULARLY_AVAILABLE_LABEL,
        DROP_SHIPPING_LABEL, LANGUAGE_TAG_LABEL, ENGLISH_LABEL, GERMAN_LABEL, SPANISH_LABEL,
        ITALIAN_LABEL, FRENCH_LABEL, PORTUGESE_LABEL, SWEDISH_LABEL };
    
    PROPERTY_COLLECTION_LABELS = new String[] { PRICING_PROPERTY_COLLECTION_LABEL,
        ARTICLE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        MARKET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        ASSET_GENERAL_INFORMATION_PROPERTY_COLLETION_LABEL,
        CAMPAIGN_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        PROMOTION_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        SUPPLIER_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        TEXTASSET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DEFAULT_X_RAY_PROPERTY_COLLECTION_LABEL, METADATA_COLLECTION_LABEL,
        UNIT_DEFAULT_PROPERTYCOLLECTION_LABEL,
        DTP_TEMPLATE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DTP_DOCUMENT_TEMPLATE_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DTP_TEMPLATE_FILE_INFOMATION_PROPERTY_COLLECTION_LABEL };
    
    TARGET_KLASS_LABELS = new String[] { MARKET_LABEL };
    
    PIM_KLASS_LABELS = new String[] { STANDARD_ARTICLE_KLASS_LABEL, STANDARD_PRODUCT_TYPES_LABEL,
        STANDARD_CHANNEL_CLASSES_LABEL, STANDARD_ATTRIBUTION_CLASSES_LABEL, STANDARD_SINGLE_ARTICLE,
        STANDARD_FILE_KLASS_LABEL, STANDARD_VERSION_KLASS_LABEL,
        STANDARD_GOLDEN_ARTICLE_KLASS_LABEL };
    
    MAM_KLASS_LABELS = new String[] { STANDARD_ATTACHMENT_KLASS_LABEL, STANDARD_ASSET_KLASS_LABEL,
        STANDARD_IMAGE_KLASS_LABEL, STANDARD_VIDEO_KLASS_LABEL, STANDARD_DOCUMENT_KLASS_LABEL,
        STANDARD_SMARTDOCUMENT_KLASS_LABEL };
    
    ROLES = new String[] { APPROVER_ROLE_LABEL, OWNER_ROLE_LABEL, SUBSCRIBER_ROLE_LABEL,
        CONTRIBUTOR_ROLE_LABEL, REVIEWER_ROLE_LABEL, SENIOR_MANAGER_ROLE_LABEL,
        ASSIGNEE_ROLE_LABEL };
    
    RELATIONSHIP_LABELS = new String[] { STANDARD_ARTICLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_MARKET_ASSET_RELATIONSHIP_LABEL, STANDARD_CAMPAIGN_ASSET_RELATIONSHIP_LABEL,
        STANDARD_CAMPAIGN_CAMPAIGN_RELATIONSHIP_LABEL, STANDARD_TEXTASSET_ASSET_RELATIONSHIP_LABEL,
        STANDARD_SUPPLIER_ASSET_RELATIONSHIP_LABEL, STANDARD_PROMOTION_ASSET_RELATIONSHIP_LABEL,
        STANDARD_ARTICLE_MARKET_RELATIONSHIP_LABEL,
        STANDARD_ARTICLE_GOLDEN_ARTICLE_RELATIONSHIP_LABEL,
        STANDARD_MARKETING_ARTICLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_MARKETING_BUNDLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_ARTICLES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_BUNDLES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_PRODUCT_TEMPLATES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_PAGE_PREVIEW_RELATIONSHIP_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_PRODUCT_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_PUBLICATION_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL };
    
    RELATIONSHIP_SIDE_1_LABELS = new String[] { ARTICLES_LABEL, MARKET_LABEL, 
        CAMPAIGN_LABEL, CAMPAIGN_LABEL, TEXTASSET_LABEL, SUPPLIER_LABEL,
        PROMOTION_LABEL, ARTICLES_LABEL, ARTICLES_LABEL,
        MARKETING_PRODUCT_LABEL, MARKETING_BUNDLE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, STANDARD_DTP_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_LABEL, STANDARD_DTP_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL, STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL };
    
    RELATIONSHIP_SIDE_2_LABELS = new String[] { IMAGES, IMAGES, IMAGES, IMAGES, IMAGES,
        CAMPAIGN_LABEL, IMAGES, IMAGES, IMAGES, MARKET_LABEL, IMAGES,
        STANDARD_GOLDEN_ARTICLE_KLASS_LABEL, IMAGES, IMAGES, MARKET_LABEL,
        IMAGES, IMAGES, IMAGES, MARKETING_PRODUCT_LABEL, MARKETING_BUNDLE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, PAGE_PREVIEWS, IMAGES,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_PRODUCT_TEMPLATE_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL, IMAGES, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL };
    
    Language_Labels = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        put(Constants.ENGLISH_US, ENGLISH_LABEL);
        put(Constants.FRENCH, FRENCH_LABEL);
        put(Constants.SPANISH, SPANISH_LABEL);
        put(Constants.GERMAN, GERMAN_LABEL);
      }
    };
    
    Tabs_Labels = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        put(SystemLevelIds.DEFAULT_DASHBOARD_TAB_ID, DEFAULT_DASHBOARD_TAB);
        put(SystemLevelIds.DEFAULT_DATA_INTEGRATION_TAB_ID, DEFAULT_DATA_INTEGRATION_TAB);
      }
    };
    
    TAGS_LABELS = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        // status
        put("statustag", STATUS_TAG_LABEL);
        put("enrichmenttag", ENRICHMENT_TAG_LABEL);
        put("qualitychecktag", QUALITY_CHECK_TAG_LABEL);
        put("translationtag", TRANSLATION_TAG_LABEL);
        put("approvaltag", APPROVAL_TAG_LABEL);
        put("productivetag", PRODUCTIVE_TAG_LABEL);
        put("blockedfromplanning", BLOCKED_FROM_PLANNING_LABEL);
        
        // availability
        put("availabilitytag", AVAILABILITY_TAG_LABEL);
        put("onrequest", ON_REQUEST_LABEL);
        put("onstock", ON_STOCK_LABEL);
        put("regularlyavailable", REGULARLY_AVAILABLE_LABEL);
        put("dropshipping", DROP_SHIPPING_LABEL);
        
        // lagnguage tag 8
        /* put("languagetag",LANGUAGE_TAG_LABEL);
        put("english",ENGLISH_LABEL);
        put("german",GERMAN_LABEL);
        put("spanish",SPANISH_LABEL);
        put("italian",ITALIAN_LABEL);
        put("french",FRENCH_LABEL);
        put("portugese",PORTUGESE_LABEL);
        put("swedish",SWEDISH_LABEL);*/
        
        // life cylcel status tag 10
        put("lifestatustag", LIFE_STATUS_TAG_LABEL);
        put("life_status_inbox", LIFE_STATUS_INBOX_LABEL);
        put("life_status_nointerest", LIFE_STATUS_NO_INTEREST_LABEL);
        put("life_status_preparation", LIFE_STATUS_PREPARATION_LABEL);
        put("life_status_active", LIFE_STATUS_ACTIVE_LABEL);
        put("life_status_activeblocked", LIFE_STATUS_ACTIVE_BLOCKED_LABEL);
        put("life_status_activebanned", LIFE_STATUS_ACTIVE_BANNED_LABEL);
        put("life_status_retired", LIFE_STATUS_RETIRED_LABEL);
        put("life_status_archived", LIFE_STATUS_ARCHIVED_LABEL);
        put("life_status_deleted", LIFE_STATUS_DELETED_LABEL);
        
        // listing status tag 8
        put("listingstatustag", LISTING_STATUS_TAG_LABEL);
        put("listing_status_catlog", LISTING_STATUS_CATLOG_LABEL);
        put("listing_status_ignored", LISTING_STATUS_IGNORED_LABEL);
        put("listing_status_rejected", LISTING_STATUS_REJECTED_LABEL);
        put("listing_status_onboardingpool", LISTING_STATUS_ONBOARDING_POOL_LABEL);
        put("listing_status_recommended", LISTING_STATUS_RECOMMENDED_LABEL);
        put("listing_status_shadowassortment", LISTING_STATUS_SHADOW_ASSORTMENT_LABEL);
        put("listing_status_listed", LISTING_STATUS_LISTED_LABEL);
        
        // system status tag 8
        put("T_STATUS_SYSTEM", T_STATUS_SYSTEM_LABEL);
        put("T_STATUS_SYSTEM_NEW", T_STATUS_SYSTEM_NEU_LABEL);
        put("T_STATUS_SYSTEM_INACTIV", T_STATUS_SYSTEM_INAKTIV_LABEL);
        put("T_STATUS_SYSTEM_ACTIV", T_STATUS_SYSTEM_AKTIV_LABEL);
        put("T_STATUS_SYSTEM_ARCHIVED", T_STATUS_SYSTEM_ARCHIVIERT_LABEL);
        put("T_STATUS_SYSTEM_DELETED", T_STATUS_SYSTEM_GELOESCHT_LABEL);
        put("T_STATUS_SYSTEM_PREPARE", T_STATUS_SYSTEM_PREPARE_LABEL);
        put("T_STATUS_SYSTEM_BLOCKED", T_STATUS_SYSTEM_BLOCKED_LABEL);
        
        // project status 9
        
        put("T_STATUS_PROJECT", T_STATUS_PROJECT_LABEL);
        put("T_STATUS_PROJECT_IN_PLANNING", T_STATUS_PROJEKT_IN_PLANUNG);
        put("T_STATUS_PROJECT_CANCELED", T_STATUS_PROJEKT_ABGEBROCHEN);
        put("T_STATUS_PROJECT_COMPLETE", T_STATUS_PROJEKT_ABGESCHLOSSEN);
        put("T_STATUS_PROJECT_ERROR_PROCESSING", T_STATUS_PROJEKT_FEHLER_BEARBEITEN);
        put("T_STATUS_PROJECT_LICENSE_MISSING", T_STATUS_PROJEKT_LIZENZ_FEHLT);
        put("T_STATUS_PROJECT_QUALITY_CHECK", T_STATUS_PROJEKT_QUALITAT_SICHERN);
        // put("T_STATUS_PROJECT_USING_ALLOWED", T_STATUS_PROJEKT_VERWENDBAR);
        put("T_STATUS_PROJECT_REWORK", T_STATUS_PROJEKT_ZUR_UBERARBEITUNG);
        
        // campaign type tag 6
        put("T_CAMP_TYPE", T_CAMP_TYPE_LABEL);
        put("T_CAMP_TYPE_NATIONAL", T_CAMP_TYPE_NATIONAL_LABEL);
        put("T_CAMP_TYPE_REGIONAL", T_CAMP_TYPE_REGIONAL_LABEL);
        put("T_CAMP_TYPE_CATALINA", T_CAMP_TYPE_CATALINA_LABEL);
        put("T_CAMP_TYPE_DCARD", T_CAMP_TYPE_DCARD_LABEL);
        put("T_CAMP_TYPE_SUPPLIER", T_CAMP_TYPE_LIEFERANT_LABEL);
        
        // task status tag 8
        put("taskstatustag", TASK_STATUS_TAG_LABEL);
        put("taskplanned", PLANNED_LABEL);
        put("taskready", READY_LABEL);
        put("taskdeclined", DECLINED_LABEL);
        put("taskinprogress", IN_PROGRESS_LABEL);
        put("taskdone", DONE_LABEL);
        put("taskverified", VERIFIED_LABEL);
        put("tasksignedoff", SIGNED_OFF_LABEL);
        
        // resolution tag 4
        put("resolutiontag", RESOLUTION_TAG_LABEL);
        put("resolution_300P", RESOLUTION_300P_LABEL);
        put("resolution_150P", RESOLUTION_150P_LABEL);
        put("resolution_72P", RESOLUTION_72P_LABEL);
        
        put("image_extension", IMAGE_EXTENSION_LABEL);
        put("image_format_jpg", IMAGE_FORMAT_JPG_LABEL);
        put("image_format_png", IMAGE_FORMAT_PNG_LABEL);
        put("image_format_original", IMAGE_FORMAT_ORIGINAL_LABEL);
        
        // boolean tag 6
        put("isordertag", IS_ORDER_TAG_LABEL);
        put("isordertagvalue", IS_ORDER_TAG_LABEL);
        put("issalestag", IS_SALES_TAG_LABEL);
        put("issalestagvalue", IS_SALES_TAG_LABEL);
        put("isbaseunittag", IS_BASEUNIT_TAG_LABEL);
        put("isbaseunittagvalue", IS_BASEUNIT_TAG_LABEL);
        
        // suported languages
        /*put("supportedLanguages", SUPPORTED_LANGUAGES);
        put("en", EN);
        put("dr", DE);
        put("es", ES);
        put("fr", FR);
        
        put("language", LANGUAGE);
        put("en_US", EN_US);
        put("en_UK", EN_UK);
        put("de_DE", DE_DE);
        put("fr_FR", FR_FR);
        put("es_ES", ES_ES);*/
        
      }
    };
    
    // Smart Documents
    SMART_DOCUMENT_LABEL = "Smart Document__de_DE";
    
    // References
    STANDARD_ARTICLE_SMART_DOCUMENT_REFRENCE_ID = "Article-Smart Document Reference__de_DE";
    STANDARD_MARKETING_ARTICLE_SMART_DOCUMENT_REFRENCE_ID = "Marketing Article-Smart Document Reference__de_DE";
    
    REFERENCE_LABELS = new String[] { STANDARD_ARTICLE_SMART_DOCUMENT_REFRENCE_ID,
        STANDARD_MARKETING_ARTICLE_SMART_DOCUMENT_REFRENCE_ID };
    
    REFERENCE_SIDE_1_LABELS = new String[] { ARTICLES_LABEL, MARKETING_PRODUCT_LABEL };
    
    REFERENCE_SIDE_2_LABELS = new String[] { SMART_DOCUMENT_LABEL, SMART_DOCUMENT_LABEL };
  }
}
