package com.cs.core.runtime.interactor.constants.projectspecific;

import java.util.HashMap;

import org.springframework.stereotype.Component;

import com.cs.constants.SystemLevelIds;
import com.cs.core.runtime.interactor.constants.application.Constants;

@Component
public class InitializeDataLabels__fr_FR extends InitializeDataLabelKeys {
  
  public InitializeDataLabels__fr_FR()
  {
    ASSET_COVERFLOW_ATTRIBUTE_LABEL = "File Preview__fr_FR";
    ADDRESS_ATTRIBUTE_LABEL = "Address__fr_FR";
    DESCRIPTION_ATTRIBUTE_LABEL = "Description__fr_FR";
    DUE_DATE_ATTRIBUTE_LABEL = "Due Date__fr_FR";
    FIRST_NAME_ATTRIBUTE_LABEL = "First Name__fr_FR";
    LIST_PRICE_ATTRIBUTE_LABEL = "List Price__fr_FR";
    LONG_DESCRIPTION_ATTRIBUTE_LABEL = "Long Description__fr_FR";
    MINIMUM_PRICE_ATTRIBUTE_LABEL = "Minimum Price__fr_FR";
    PID_ATTRIBUTE_LABEL = "PID__fr_FR";
    PIN_CODE_ATTRIBUTE_LABEL = "Pin Code__fr_FR";
    SELLING_PRICE_ATTRIBUTE_LABEL = "Selling Price__fr_FR";
    SHORT_DESCRIPTION_ATTRIBUTE_LABEL = "Short Description__fr_FR";
    SKU_ATTRIBUTE_LABEL = "SKU__fr_FR";
    TELEPHONE_NUMBER_ATTRIBUTE_LABEL = "Telephone Number__fr_FR";
    DISCOUNT_ATTRIBUTE_LABEL = "Discount (%)__fr_FR";
    GTIN_ATTRIBUTE_LABEL = "GTIN__fr_FR";
    LAST_NAME_ATTRIBUTE_LABEL = "Last Name__fr_FR";
    MAXIMUM_PRICE_ATTRIBUTE_LABEL = "Maximum Price__fr_FR";
    
    CREATED_BY_ATTRIBUTE = "Created By__fr_FR";
    CREATED_ON_ATTRIBUTE = "Created On__fr_FR";
    LAST_MODIFIED_ATTRIBUTE = "Last Modified__fr_FR";
    LAST_MODIFIED_BY_ATTRIBUTE = "Last Modified By__fr_FR";
    NAME_ATTRIBUTE = "Name__fr_FR";
    
    DTP_ERROR_MARGIN_LABEL = "Error margin__fr_FR";
    DTP_MAX_NO_OF_SLOTS_ATTRIBUTE_LABEL = "Maximum Number of Slots__fr_FR";
    DTP_MINIMUM_SLOT_HEIGHT_ATTRIBUTE_LABEL = "Minimum Slot Height__fr_FR";
    DTP_MINIMUM_SLOT_WIDTH_ATTRIBUTE_LABEL = "Minimum Slot Width__fr_FR";
    DTP_DELTA_ATTRIBUTE_LABEL = "Delta__fr_FR";
    
    I_META_FILE_NAME = "I_META_FILE_NAME__fr_FR";
    I_META_DOCUMENT_TYPE = "I_META_DOCUMENT_TYPE__fr_FR";
    I_APPLICATION = "I_APPLICATION__fr_FR";
    I_CREATE_DATE = "I_CREATE_DATE__fr_FR";
    I_MODIFICATION_DATE = "I_MODIFICATION_DATE__fr_FR";
    I_META_FILE_SIZE = "I_META_FILE_SIZE__fr_FR";
    I_DIMENSIONS = "I_DIMENSIONS__fr_FR";
    I_DIMENSION_IN_INCH = "I_DIMENSION_IN_INCH__fr_FR";
    I_RESOLUTION = "I_RESOLUTION__fr_FR";
    I_BIT_DEPTH = "I_BIT_DEPTH__fr_FR";
    I_COLOR_MODE = "I_COLOR_MODE__fr_FR";
    I_COLOR_PROFILE = "I_COLOR_PROFILE__fr_FR";
    I_META_CREATOR_AUTHOR = "I_META_CREATOR_AUTHOR__fr_FR";
    I_META_CREATOR_STREET = "I_META_CREATOR_STREET__fr_FR";
    I_META_CREATOR_LOCATION = "I_META_CREATOR_LOCATION__fr_FR";
    I_META_CREATOR_STATE = "I_META_CREATOR_STATE__fr_FR";
    I_META_CREATOR_POSTAL_CODE = "I_META_CREATOR_POSTAL_CODE__fr_FR";
    I_META_CREATOR_COUNTRY = "I_META_CREATOR_COUNTRY__fr_FR";
    I_META_CREATOR_TEL = "I_META_CREATOR_TEL__fr_FR";
    I_META_CREATOR_EMAIL = "I_META_CREATOR_EMAIL__fr_FR";
    I_META_CREATOR_WWW = "I_META_CREATOR_WWW__fr_FR";
    I_META_HEADING = "I_META_HEADING__fr_FR";
    I_META_DESCRIPTION = "I_META_DESCRIPTION__fr_FR";
    I_META_KEYWORDS = "I_META_KEYWORDS__fr_FR";
    I_META_LOCATION_DETAIL = "I_META_LOCATION_DETAIL__fr_FR";
    I_META_LOCATION = "I_META_LOCATION__fr_FR";
    I_META_STATE = "I_META_STATE__fr_FR";
    I_META_COUNTRY = "I_META_COUNTRY__fr_FR";
    I_META_TITEL = "I_META_TITEL__fr_FR";
    I_META_COPYRIGHT = "I_META_COPYRIGHT__fr_FR__fr_FR";
    I_META_COPYRIGHT_STATUS = "I_META_COPYRIGHT_STATUS__fr_FR";
    I_META_EXPOSURE_INDEX = "I_META_EXPOSURE_INDEX__fr_FR";
    I_META_FOCAL_RANGE = "I_META_FOCAL_RANGE__fr_FR";
    I_META_MAX_BLINDING_VALUE = "I_META_MAX_BLINDING_VALUE__fr_FR";
    I_META_RECORDING_DATE = "I_META_RECORDING_DATE__fr_FR";
    I_META_EXPOSURE_CONTROLS = "I_META_EXPOSURE_CONTROLS__fr_FR";
    I_META_LIGHT_SOURCE = "I_META_LIGHT_SOURCE__fr_FR";
    I_META_SENSOR_TYPE = "I_META_SENSOR_TYPE__fr_FR";
    I_META_BRAND = "I_META_BRAND__fr_FR";
    I_META_MODELL = "I_META_MODELL__fr_FR";
    I_META_SERIAL_NUMBER = "I_META_SERIAL_NUMBER__fr_FR";
    I_META_PIXEL_X_DIMENSION = "I_META_PIXEL_X_DIMENSION__fr_FR";
    I_META_PIXEL_Y_DIMENSION = "I_META_PIXEL_Y_DIMENSION__fr_FR";
    I_META_HIGH_RESOLUTION = "I_META_HIGH_RESOLUTION__fr_FR";
    I_META_WIDTH_RESOLUTION = "I_META_WIDTH_RESOLUTION__fr_FR";
    I_META_X_RESOLUTION = "I_META_X_RESOLUTION__fr_FR";
    I_META_Y_RESOLUTION = "I_META_Y_RESOLUTION__fr_FR";
    
    // Tags
    IS_ORDER_TAG_LABEL = "isOrder__fr_FR";
    IS_SALES_TAG_LABEL = "isSales__fr_FR";
    IS_BASEUNIT_TAG_LABEL = "isBaseUnit__fr_FR";
    
    LISTING_STATUS_TAG_LABEL = "Statut de la liste";
    LISTING_STATUS_CATLOG_LABEL = "Catalogue";
    LISTING_STATUS_IGNORED_LABEL = "Ignoré";
    LISTING_STATUS_REJECTED_LABEL = "Rejeté";
    LISTING_STATUS_ONBOARDING_POOL_LABEL = "Portail Collaboratif";
    LISTING_STATUS_RECOMMENDED_LABEL = "Recommandé";
    LISTING_STATUS_SHADOW_ASSORTMENT_LABEL = "Assortiment Caché";
    LISTING_STATUS_LISTED_LABEL = "Listé";
    LIFE_STATUS_TAG_LABEL = "Statut du cycle de vie";
    LIFE_STATUS_INBOX_LABEL = "Réceptionné";
    LIFE_STATUS_NO_INTEREST_LABEL = "Sans intérêt";
    LIFE_STATUS_PREPARATION_LABEL = "Préparation";
    LIFE_STATUS_ACTIVE_LABEL = "Actif";
    LIFE_STATUS_ACTIVE_BLOCKED_LABEL = "Activé - Bloqué";
    LIFE_STATUS_ACTIVE_BANNED_LABEL = "Activé - Banni";
    LIFE_STATUS_RETIRED_LABEL = "Retiré";
    LIFE_STATUS_ARCHIVED_LABEL = "Archivé";
    LIFE_STATUS_DELETED_LABEL = "Deleted__fr_FR";
    STATUS_TAG_LABEL = "Status__fr_FR";
    ENRICHMENT_TAG_LABEL = "Enrichment__fr_FR";
    QUALITY_CHECK_TAG_LABEL = "Quality Check__fr_FR";
    TRANSLATION_TAG_LABEL = "Translation__fr_FR";
    APPROVAL_TAG_LABEL = "Approval__fr_FR";
    PRODUCTIVE_TAG_LABEL = "Productive__fr_FR";
    BLOCKED_FROM_PLANNING_LABEL = "Blocked from planning__fr_FR";
    AVAILABILITY_TAG_LABEL = "Availability__fr_FR";
    ON_REQUEST_LABEL = "On Request__fr_FR";
    ON_STOCK_LABEL = "On Stock__fr_FR";
    REGULARLY_AVAILABLE_LABEL = "Regularly Available__fr_FR";
    DROP_SHIPPING_LABEL = "Drop Shipping__fr_FR";
    LANGUAGE_TAG_LABEL = "Language__fr_FR";
    ENGLISH_LABEL = "Anglais";
    GERMAN_LABEL = "Allemand";
    SPANISH_LABEL = "Espanol";
    ITALIAN_LABEL = "Italian__fr_FR";
    FRENCH_LABEL = "Français";
    PORTUGESE_LABEL = "Portugese__fr_FR";
    SWEDISH_LABEL = "Swedish__fr_FR";
    
    SUPPORTED_LANGUAGES = "SupportedLanguages__fr_FR";
    EN = "en__fr_FR";
    DE = "de__fr_FR";
    FR = "fr__fr_FR";
    ES = "es__fr_FR";
    
    LANGUAGE = "language__fr_FR";
    EN_US = "English (U.S)__fr_FR";
    EN_UK = "English (U.K)__fr_FR";
    DE_DE = "Deutsch__fr_FR";
    FR_FR = "Fran�ais__fr_FR";
    ES_ES = "Espa�ol__fr_FR";
    
    DEFAULT_DATA_INTEGRATION_TAB = "DefaultDataIntegrationTab__fr_FR";
    DEFAULT_DASHBOARD_TAB = "DefaultDashboardTab__fr_FR";
    
    T_STATUS_SYSTEM_LABEL = "Status__fr_FR";
    T_STATUS_SYSTEM_NEU_LABEL = "Neu__fr_FR";
    T_STATUS_SYSTEM_INAKTIV_LABEL = "Inaktiv__fr_FR";
    T_STATUS_SYSTEM_AKTIV_LABEL = "Aktiv__fr_FR";
    T_STATUS_SYSTEM_ARCHIVIERT_LABEL = "Archiviert__fr_FR";
    T_STATUS_SYSTEM_GELOESCHT_LABEL = "GelÃ¶scht__fr_FR";
    T_STATUS_SYSTEM_PREPARE_LABEL = "Vorbereitung__fr_FR";
    T_STATUS_SYSTEM_BLOCKED_LABEL = "Gesperrt__fr_FR";
    T_STATUS_PROJECT_LABEL = "Projektstatus__fr_FR";
    
    T_CAMPAIGN_GOALS_LABEL = "Goals__fr_FR";
    T_GOALS_BRAND_PROMOTION_LABEL = "Brand Promotion__fr_FR";
    T_GOALS_SEASONAL_PROMOTION_LABEL = "Seasonal Promotion__fr_FR";
    T_GOALS_NEW_ARRIVALS_LABEL = "New Arrivals__fr_FR";
    T_GOALS_PROMOTION_HIGH_MARGIN_LABEL = "Promotion of Higher Margin Products__fr_FR";
    T_GOALS_INVENTORY_CLEARANCE_LABEL = "Inventory Clearance__fr_FR";
    T_GOALS_LOYALTY_POINTS_LABEL = "Niche group promotion (Loyalty Points)__fr_FR";
    T_GOALS_SPECIAL_TOPIC_LABEL = "Special topic promotion__fr_FR";
    T_GOALS_ACQUIRE_NEW_CUSTOMERS_LABEL = "Acquire new customers__fr_FR";
    T_GOALS_RETAIN_EXISTING_CUSTOMERS_LABEL = "Retain existing customers__fr_FR";
    
    T_CAMP_TYPE_LABEL = "Kampagnen-Typ__fr_FR";
    T_CAMP_TYPE_NATIONAL_LABEL = "National__fr_FR";
    T_CAMP_TYPE_REGIONAL_LABEL = "Regional__fr_FR";
    T_CAMP_TYPE_CATALINA_LABEL = "Catalina__fr_FR";
    T_CAMP_TYPE_DCARD_LABEL = "DeutschlandCard__fr_FR";
    T_CAMP_TYPE_LIEFERANT_LABEL = "Lieferant__fr_FR";
    TASK_STATUS_TAG_LABEL = "Task-Status__fr_FR";
    PLANNED_LABEL = "Planned__fr_FR";
    READY_LABEL = "Ready__fr_FR";
    DECLINED_LABEL = "Declined__fr_FR";
    IN_PROGRESS_LABEL = "In_Progress__fr_FR";
    DONE_LABEL = "Done__fr_FR";
    VERIFIED_LABEL = "Verified__fr_FR";
    SIGNED_OFF_LABEL = "Signed_Off__fr_FR";
    
    RESOLUTION_TAG_LABEL = "Resolution__fr_FR";
    RESOLUTION_300P_LABEL = "300_dpi__fr_FR";
    RESOLUTION_150P_LABEL = "150_dpi__fr_FR";
    RESOLUTION_72P_LABEL = "72_dpi__fr_FR";
    IMAGE_EXTENSION_LABEL = "Image Extension__fr_FR";
    IMAGE_FORMAT_JPG_LABEL = "jpg__fr_FR";
    IMAGE_FORMAT_PNG_LABEL = "png__fr_FR";
    IMAGE_FORMAT_ORIGINAL_LABEL = "original__fr_FR";
    
    T_STATUS_PROJEKT_VERWENDBAR = "Verwendbar";
    T_STATUS_PROJEKT_IN_PLANUNG = "In Planung";
    T_STATUS_PROJEKT_ABGESCHLOSSEN = "abgeschlossen";
    T_STATUS_PROJEKT_ZUR_UBERARBEITUNG = "zur Ãœberarbeitung";
    T_STATUS_PROJEKT_QUALITAT_SICHERN = "QualitÃ¤t sichern";
    T_STATUS_PROJEKT_FEHLER_BEARBEITEN = "Fehler bearbeiten";
    T_STATUS_PROJEKT_LIZENZ_FEHLT = "Lizenz fehlt";
    T_STATUS_PROJEKT_ABGEBROCHEN = "abgebrochen";
    
    CREATED_EVENT_LABEL = "Created__fr_FR";
    
    LANGUAGE_TAXONOMY_LABEL = "Language__fr_FR";
    
    PRICING_PROPERTY_COLLECTION_LABEL = "Pricing__fr_FR";
    ARTICLE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "General Information__fr_FR";
    MARKET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Market General Information__fr_FR";
    ASSET_GENERAL_INFORMATION_PROPERTY_COLLETION_LABEL = "Asset Information__fr_FR";
    CAMPAIGN_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "General Information__fr_FR";
    PROMOTION_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Promotion General Information__fr_FR";
    SUPPLIER_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Supplier General Information__fr_FR";
    TEXTASSET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Text-Asset General Information__fr_FR";
    DEFAULT_X_RAY_PROPERTY_COLLECTION_LABEL = "Default X-Ray Collection__fr_FR";
    METADATA_COLLECTION_LABEL = "Metadata__fr_FR";
    UNIT_DEFAULT_PROPERTYCOLLECTION_LABEL = "Unit Information__fr_FR";
    DTP_TEMPLATE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Template General Information__fr_FR";
    DTP_DOCUMENT_TEMPLATE_INFORMATION_PROPERTY_COLLECTION_LABEL = "Document Template Information__fr_FR";
    DTP_TEMPLATE_FILE_INFOMATION_PROPERTY_COLLECTION_LABEL = "Template File Information__fr_FR";
    
    STANDARD_ARTICLE_KLASS_LABEL = "Article__fr_FR";
    STANDARD_SET_KLASS_LABEL = "Set__fr_FR";
    STANDARD_COLLETION_KLASS_LABEL = "Collection__fr_FR";
    STANDARD_CHANNEL_CLASSES_LABEL = "Channel Classes__fr_FR";
    STANDARD_PRODUCT_TYPES_LABEL = "Product Types__fr_FR";
    STANDARD_SINGLE_ARTICLE = "Single Article__fr_FR";
    STANDARD_ATTRIBUTION_CLASSES_LABEL = "Attribution Classes__fr_FR";
    STANDARD_VERSION_KLASS_LABEL = "Version Class__fr_FR";
    STANDARD_GOLDEN_ARTICLE_KLASS_LABEL = "Golden Article__fr_FR";
    
    MARKETING_PRODUCT_LABEL = "Marketing Product__fr_FR";
    MARKETING_BUNDLE_LABEL = "Marketing Bundle__fr_FR";    
    PROMOTION_LABEL = "Promotion";
    SUPPLIER_LABEL = "Supplier__fr_FR";
    MARKET_LABEL = "Marché";
    STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL = "PublicationTemplate__fr_FR";
    STANDARD_DTP_PUBLICATION_LABEL = "Publication__fr_FR";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL = "DocumentTemplate__fr_FR";
    STANDARD_DTP_PRODUCT_TEMPLATE_LABEL = "ProductTemplate__fr_FR";
    STANDARD_DTP_ABSTRACT_DOCUMENT_TEMPLATE_LABEL = "Abstract Document Template__fr_FR";
    STANDARD_DTP_ABSTRACT_PRODUCT_TEMPLATE_LABEL = "Abstract Product Template__fr_FR";
    STANDARD_DTP_ABSTRACT_PUBLICATION_TEMPLATE_LABEL = "Abstract Publication Template__fr_FR";
    STANDARD_DTP_ABSTRACT_PUBLICATION_LABEL = "Abstract Publication__fr_FR";
    STANDARD_DTP_ABSTRACT_DOCUMENT_LABEL = "Abstract Document__fr_FR";
    STANDARD_DTP_DOCUMENT_LABEL = "Document__fr_FR";
    STANDARD_DTP_DOCUMENT_VARIANT_LABEL = "Document Variant__fr_FR";
    
    STANDARD_FILE_KLASS_LABEL = "Fichier";
    
    ADMIN_LABEL = "Administrateur";
    
    STANDARD_PROPERTY_COLLECTION_TAB_LABEL = "Properties__fr_FR";
    STANDARD_RELATIONSHIP_TAB_LABEL = "Relationships__fr_FR";
    STANDARD_CONTEXT_TAB_LABEL = "Contexts__fr_FR";
    STANDARD_TASK_TAB_LABEL = "Tasks__fr_FR";
    STANDARD_TIMELINE_TAB_LABEL = "Timeline__fr_FR";
    STANDARD_RENDITION_TAB_LABEL = "Renditions__fr_FR";
    STANDARD_OVERVIEW_TAB_LABEL = "Overview__fr_FR";
    STANDARD_MDM_TAB_LABEL = "Mdm__fr_FR";
    
    SUPPLIERS_LABEL = "Supplier__fr_FR";
    MARKETPLACES_LABEL = "Marketplaces__fr_FR";
    DISTRIBUTORS_LABEL = "Distributors__fr_FR";
    WHOLESALERS_LABEL = "Wholesalers__fr_FR";
    TRANSLATION_AGENCY_LABEL = "Translation Agency__fr_FR";
    CONTENT_ENRICHMENT_AGENCY_LABEL = "Content Enrichment Agency__fr_FR";
    DIGITAL_ASSET_AGENCY_LABEL = "Digital Asset Agency__fr_FR";
    
    // Role
    RESPONSIBLE_ROLE_LABEL = "Responsible__fr_FR";
    ACCOUNTABLE_ROLE_LABEL = "Accountable__fr_FR";
    CONSULTED_ROLE_LABEL = "Consulted__fr_FR";
    INFORMED_ROLE_LABEL = "Informed__fr_FR";
    VERIFY_ROLE_LABEL = "Verify__fr_FR";
    SIGNOFF_ROLE_LABEL = "Sign-off__fr_FR";
    ADMIN_ROLE_LABEL = "Admin__fr_FR";
    
    RACIVS_ROLE_LABELS = new String[] { RESPONSIBLE_ROLE_LABEL, ACCOUNTABLE_ROLE_LABEL,
        CONSULTED_ROLE_LABEL, INFORMED_ROLE_LABEL, VERIFY_ROLE_LABEL, SIGNOFF_ROLE_LABEL,
        ADMIN_ROLE_LABEL };
    SWEDISH_LABEL = "Swedish__fr_FR";
    
    CREATED_EVENT_LABEL = "Created__fr_FR";
    
    PRICING_PROPERTY_COLLECTION_LABEL = "Pricing__fr_FR";
    ARTICLE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "General Information__fr_FR";
    MARKET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Market General Information__fr_FR";
    ASSET_GENERAL_INFORMATION_PROPERTY_COLLETION_LABEL = "Asset Information__fr_FR";
    CAMPAIGN_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Campaign General Information__fr_FR";
    PROMOTION_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Promotion General Information__fr_FR";
    SUPPLIER_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Supplier General Information__fr_FR";
    TEXTASSET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Text-Asset General Information__fr_FR";
    DEFAULT_X_RAY_PROPERTY_COLLECTION_LABEL = "Default X-Ray Collection__fr_FR";
    METADATA_COLLECTION_LABEL = "Metadata__fr_FR";
    
    STANDARD_ARTICLE_KLASS_LABEL = "Article";
    STANDARD_SET_KLASS_LABEL = "Ensemble";
    STANDARD_COLLETION_KLASS_LABEL = "Collection__fr_FR";
    STANDARD_CHANNEL_CLASSES_LABEL = "Channel Classes__fr_FR";
    STANDARD_PRODUCT_TYPES_LABEL = "Product Types__fr_FR";
    STANDARD_SINGLE_ARTICLE = "Single Article__fr_FR";
    STANDARD_ATTRIBUTION_CLASSES_LABEL = "Attribution Classes__fr_FR";
    STANDARD_VERSION_KLASS_LABEL = "Version__fr_FR";
    
    STANDARD_VIDEO_KLASS_LABEL = "Video__fr_FR";
    STANDARD_DOCUMENT_KLASS_LABEL = "Document__fr_FR";
    STANDARD_IMAGE_KLASS_LABEL = "Image__fr_FR";
    STANDARD_ATTACHMENT_KLASS_LABEL = "Attachment__fr_FR";
    STANDARD_ASSET_KLASS_LABEL = "Objet";
    STANDARD_SMARTDOCUMENT_KLASS_LABEL = "Smart Document__fr_FR";
    
    STANDARD_CAMPAIGN_KLASS_LABEL = "Campagne";
    
    PROMOTION_LABEL = "Promotion__fr_FR";
    SUPPLIER_LABEL = "Supplier__fr_FR";
    MARKET_LABEL = "Market__fr_FR";
    
    APPROVER_ROLE_LABEL = "Approver(Sign-Off)__fr_FR";
    OWNER_ROLE_LABEL = "Owner(Responsible)__fr_FR";
    SUBSCRIBER_ROLE_LABEL = "Subscriber(Informed)__fr_FR";
    CONTRIBUTOR_ROLE_LABEL = "Contributor(Consulted)__fr_FR";
    REVIEWER_ROLE_LABEL = "Reviewer(Verify)__fr_FR";
    SENIOR_MANAGER_ROLE_LABEL = "Senior Manager(Accountable)__fr_FR";
    ASSIGNEE_ROLE_LABEL = "Assignee__fr_FR";
    
    STANDARD_ARTICLE_ASSET_RELATIONSHIP_LABEL = "Article-Asset Relationship__fr_FR";
    STANDARD_MARKET_ASSET_RELATIONSHIP_LABEL = "Market-Asset Relationship__fr_FR";
    STANDARD_CAMPAIGN_ASSET_RELATIONSHIP_LABEL = "Campaign-Asset Relationship__fr_FR";
    STANDARD_CAMPAIGN_CAMPAIGN_RELATIONSHIP_LABEL = "Campaign-Campaign Relationship__fr_FR";
    STANDARD_TEXTASSET_ASSET_RELATIONSHIP_LABEL = "TextAsset-Asset Relationship__fr_FR";
    STANDARD_SUPPLIER_ASSET_RELATIONSHIP_LABEL = "Supplier-Asset Relationship__fr_FR";
    STANDARD_PROMOTION_ASSET_RELATIONSHIP_LABEL = "Promotion-Asset Relationship__fr_FR";
    STANDARD_ARTICLE_MARKET_RELATIONSHIP_LABEL = "Artikel MÃ¤rkte__fr_FR";
    STANDARD_ARTICLE_GOLDEN_ARTICLE_RELATIONSHIP_LABEL = "Article-GoldenArticle Relationship__fr_FR";
    STANDARD_ARTICLE_MARKETING_ARTICLE_RELATIONSHIP_LABEL = "Article-MarketingArticle Relationship__fr_FR";
    
    STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_LABEL = "PublicationTemplate - DocumentTemplate Relationship__fr_FR";
    STANDARD_DTP_PRODUCT_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "Product Template - Asset Relationship__fr_FR";
    STANDARD_DTP_PUBLICATION_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "Publication Template - Asset Relationship__fr_FR";
    STANDARD_DTP_DOCUMENT_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "DocumentTemplate - Asset Relationship__fr_FR";
    STANDARD_DTP_DOCUMENT_TEMPLATE_PAGE_PREVIEW_RELATIONSHIP_LABEL = "DocumentTemplate - Page Preview Relationship__fr_FR";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_ARTICLES_RELATIONSHIP_LABEL = "DocumentTemplate - Marketing Articles Relationship__fr_FR";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_PRODUCT_TEMPLATES_RELATIONSHIP_LABEL = "DocumentTemplate - Product Template Relationship__fr_FR";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_BUNDLE_RELATIONSHIP_LABEL = "DocumentTemplate - Marketing Bundle Relationship__fr_FR";
    STANDARD_DTP_PUBLICATION_DTP_PUBLICATION_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Publication Template__fr_FR";
    STANDARD_DTP_PUBLICATION_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Document Template__fr_FR";
    STANDARD_DTP_PUBLICATION_DTP_PRODUCT_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Product Template__fr_FR";
    STANDARD_MARKETING_ARTICLE_ASSET_RELATIONSHIP_LABEL = "MarketingArticle - Asset Relationship__fr_FR";
    STANDARD_MARKETING_BUNDLE_ASSET_RELATIONSHIP_LABEL = "MarketingBundle - Asset Relationship__fr_FR";
    
    PAGE_PREVIEWS = "Page Previews__fr_FR";
    
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_ARTICLES_RELATIONSHIP_LABEL = "Document Template - Marketing Article__fr_FR";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_BUNDLES_RELATIONSHIP_LABEL = "Document Template - Marketing Bundle__fr_FR";
    STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL = "Publication Template - Document Template__fr_FR";
    
    // _LABEL = "side 1__fr_FR" ;
    ARTICLES_LABEL = "Articles__fr_FR";
    TARGETS_LABEL = "Targets__fr_FR";
    CAMPAIGN_LABEL = "Campaign__fr_FR";
    TEXTASSET_LABEL = "TextAsset__fr_FR";
    SUPPLIER_LABEL = "Fournisseur";
    PROMOTION_LABEL = "Promotion__fr_FR";
    
    IMAGES = "Images__fr_FR";
    
    STANDARD_ORGANIZATION = "Standard Organization__fr_FR";
    
    STANDARD_OVERVIEW_TAB_LABEL = "overview_tab__fr_FR";
    STANDARD_MDM_TAB_LABEL = "mdm_tab__fr_FR";
    STANDARD_DUPLICATE_TAB_LABEL = "duplicates_tab__fr_FR";
    STANDARD_PROPERTY_COLLECTION_TAB_LABEL = "property_collection_tab__fr_FR";
    STANDARD_RELATIONSHIP_TAB_LABEL = "relationship_tab__fr_FR";
    STANDARD_CONTEXT_TAB_LABEL = "context_tab__fr_FR";
    STANDARD_TASK_TAB_LABEL = "task_tab__fr_FR";
    STANDARD_TIMELINE_TAB_LABEL = "timeline_tab__fr_FR";
    STANDARD_RENDITION_TAB_LABEL = "renditions_tab__fr_FR";
    STANDARD_CONFIGURATION_TAB_LABEL = "configurations_tab__fr_FR";
    
    STANDARD_TAB_LABELS = new String[] { STANDARD_OVERVIEW_TAB_LABEL,
        STANDARD_PROPERTY_COLLECTION_TAB_LABEL, STANDARD_RELATIONSHIP_TAB_LABEL,
        STANDARD_CONTEXT_TAB_LABEL, STANDARD_TASK_TAB_LABEL, 
        STANDARD_TIMELINE_TAB_LABEL, STANDARD_RENDITION_TAB_LABEL,
        STANDARD_CONFIGURATION_TAB_LABEL, STANDARD_MDM_TAB_LABEL, STANDARD_DUPLICATE_TAB_LABEL };
    
    DTP_KLASS_LABELS = new String[] { STANDARD_DTP_ABSTRACT_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_ABSTRACT_PRODUCT_TEMPLATE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, STANDARD_DTP_ABSTRACT_PUBLICATION_TEMPLATE_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL };
    
    DTP_PUBLICATION_LABELS = new String[] { STANDARD_DTP_ABSTRACT_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_LABEL };
    
    DTP_DOCUMENT_LABELS = new String[] { STANDARD_DTP_ABSTRACT_DOCUMENT_LABEL,
        STANDARD_DTP_DOCUMENT_LABEL, STANDARD_DTP_DOCUMENT_VARIANT_LABEL };
    
    ATTRIBUTE_LABELS = new String[] { ASSET_COVERFLOW_ATTRIBUTE_LABEL, ADDRESS_ATTRIBUTE_LABEL,
        DESCRIPTION_ATTRIBUTE_LABEL, DUE_DATE_ATTRIBUTE_LABEL, FIRST_NAME_ATTRIBUTE_LABEL,
        LIST_PRICE_ATTRIBUTE_LABEL, LONG_DESCRIPTION_ATTRIBUTE_LABEL, MINIMUM_PRICE_ATTRIBUTE_LABEL,
        PID_ATTRIBUTE_LABEL, PIN_CODE_ATTRIBUTE_LABEL, SELLING_PRICE_ATTRIBUTE_LABEL,
        SHORT_DESCRIPTION_ATTRIBUTE_LABEL, SKU_ATTRIBUTE_LABEL, TELEPHONE_NUMBER_ATTRIBUTE_LABEL,
        DISCOUNT_ATTRIBUTE_LABEL, GTIN_ATTRIBUTE_LABEL, LAST_NAME_ATTRIBUTE_LABEL,
        MAXIMUM_PRICE_ATTRIBUTE_LABEL, CREATED_BY_ATTRIBUTE, CREATED_ON_ATTRIBUTE,
        LAST_MODIFIED_ATTRIBUTE, LAST_MODIFIED_BY_ATTRIBUTE, NAME_ATTRIBUTE,
        DTP_MAX_NO_OF_SLOTS_ATTRIBUTE_LABEL, DTP_MINIMUM_SLOT_WIDTH_ATTRIBUTE_LABEL,
        DTP_MINIMUM_SLOT_HEIGHT_ATTRIBUTE_LABEL, DTP_ERROR_MARGIN_LABEL,
        DTP_DELTA_ATTRIBUTE_LABEL };
    
    METADATA_ATTRIBUTES_LABELS = new String[] { I_META_FILE_NAME, I_META_DOCUMENT_TYPE,
        I_APPLICATION, I_CREATE_DATE, I_MODIFICATION_DATE, I_META_FILE_SIZE, I_DIMENSIONS,
        I_DIMENSION_IN_INCH, I_RESOLUTION, I_BIT_DEPTH, I_COLOR_MODE, I_COLOR_PROFILE,
        I_META_CREATOR_AUTHOR, I_META_CREATOR_STREET, I_META_CREATOR_LOCATION, I_META_CREATOR_STATE,
        I_META_CREATOR_POSTAL_CODE, I_META_CREATOR_COUNTRY, I_META_CREATOR_TEL,
        I_META_CREATOR_EMAIL, I_META_CREATOR_WWW, I_META_HEADING, I_META_DESCRIPTION,
        I_META_KEYWORDS, I_META_LOCATION_DETAIL, I_META_LOCATION, I_META_STATE, I_META_COUNTRY,
        I_META_TITEL, I_META_COPYRIGHT, I_META_COPYRIGHT_STATUS, I_META_EXPOSURE_INDEX,
        I_META_FOCAL_RANGE, I_META_MAX_BLINDING_VALUE, I_META_RECORDING_DATE,
        I_META_EXPOSURE_CONTROLS, I_META_LIGHT_SOURCE, I_META_SENSOR_TYPE, I_META_BRAND,
        I_META_MODELL, I_META_SERIAL_NUMBER, I_META_PIXEL_X_DIMENSION, I_META_PIXEL_Y_DIMENSION,
        I_META_HIGH_RESOLUTION, I_META_WIDTH_RESOLUTION, I_META_X_RESOLUTION, I_META_Y_RESOLUTION };
    
    TAG_LABELS = new String[] { LISTING_STATUS_TAG_LABEL, LISTING_STATUS_CATLOG_LABEL,
        LISTING_STATUS_IGNORED_LABEL, LISTING_STATUS_REJECTED_LABEL,
        LISTING_STATUS_ONBOARDING_POOL_LABEL, LISTING_STATUS_RECOMMENDED_LABEL,
        LISTING_STATUS_SHADOW_ASSORTMENT_LABEL, LISTING_STATUS_LISTED_LABEL, LIFE_STATUS_TAG_LABEL,
        LIFE_STATUS_INBOX_LABEL, LIFE_STATUS_NO_INTEREST_LABEL, LIFE_STATUS_PREPARATION_LABEL,
        LIFE_STATUS_ACTIVE_LABEL, LIFE_STATUS_ACTIVE_BLOCKED_LABEL, LIFE_STATUS_ACTIVE_BANNED_LABEL,
        LIFE_STATUS_RETIRED_LABEL, LIFE_STATUS_ARCHIVED_LABEL, LIFE_STATUS_DELETED_LABEL,
        STATUS_TAG_LABEL, ENRICHMENT_TAG_LABEL, QUALITY_CHECK_TAG_LABEL, TRANSLATION_TAG_LABEL,
        APPROVAL_TAG_LABEL, PRODUCTIVE_TAG_LABEL, BLOCKED_FROM_PLANNING_LABEL,
        AVAILABILITY_TAG_LABEL, ON_REQUEST_LABEL, ON_STOCK_LABEL, REGULARLY_AVAILABLE_LABEL,
        DROP_SHIPPING_LABEL, LANGUAGE_TAG_LABEL, ENGLISH_LABEL, GERMAN_LABEL, SPANISH_LABEL,
        ITALIAN_LABEL, FRENCH_LABEL, PORTUGESE_LABEL, SWEDISH_LABEL };
    
    PROPERTY_COLLECTION_LABELS = new String[] { PRICING_PROPERTY_COLLECTION_LABEL,
        ARTICLE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        MARKET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        ASSET_GENERAL_INFORMATION_PROPERTY_COLLETION_LABEL,
        CAMPAIGN_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        PROMOTION_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        SUPPLIER_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        TEXTASSET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DEFAULT_X_RAY_PROPERTY_COLLECTION_LABEL, METADATA_COLLECTION_LABEL,
        UNIT_DEFAULT_PROPERTYCOLLECTION_LABEL,
        DTP_TEMPLATE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DTP_DOCUMENT_TEMPLATE_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DTP_TEMPLATE_FILE_INFOMATION_PROPERTY_COLLECTION_LABEL };
    
    TARGET_KLASS_LABELS = new String[] { MARKET_LABEL };
    
    PIM_KLASS_LABELS = new String[] { STANDARD_ARTICLE_KLASS_LABEL, STANDARD_PRODUCT_TYPES_LABEL,
        STANDARD_CHANNEL_CLASSES_LABEL, STANDARD_ATTRIBUTION_CLASSES_LABEL,
        STANDARD_FILE_KLASS_LABEL, STANDARD_SINGLE_ARTICLE, STANDARD_VERSION_KLASS_LABEL,
        STANDARD_GOLDEN_ARTICLE_KLASS_LABEL };
    
    MAM_KLASS_LABELS = new String[] { STANDARD_ATTACHMENT_KLASS_LABEL, STANDARD_ASSET_KLASS_LABEL,
        STANDARD_IMAGE_KLASS_LABEL, STANDARD_VIDEO_KLASS_LABEL, STANDARD_DOCUMENT_KLASS_LABEL,
        STANDARD_SMARTDOCUMENT_KLASS_LABEL };
    
    ROLES = new String[] { APPROVER_ROLE_LABEL, OWNER_ROLE_LABEL, SUBSCRIBER_ROLE_LABEL,
        CONTRIBUTOR_ROLE_LABEL, REVIEWER_ROLE_LABEL, SENIOR_MANAGER_ROLE_LABEL,
        ASSIGNEE_ROLE_LABEL };
    
    RELATIONSHIP_LABELS = new String[] { STANDARD_ARTICLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_MARKET_ASSET_RELATIONSHIP_LABEL, STANDARD_CAMPAIGN_ASSET_RELATIONSHIP_LABEL,
        STANDARD_CAMPAIGN_CAMPAIGN_RELATIONSHIP_LABEL, STANDARD_TEXTASSET_ASSET_RELATIONSHIP_LABEL,
        STANDARD_SUPPLIER_ASSET_RELATIONSHIP_LABEL, STANDARD_PROMOTION_ASSET_RELATIONSHIP_LABEL,
        STANDARD_ARTICLE_MARKET_RELATIONSHIP_LABEL,
        STANDARD_ARTICLE_GOLDEN_ARTICLE_RELATIONSHIP_LABEL,
        STANDARD_MARKETING_ARTICLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_MARKETING_BUNDLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_ARTICLES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_BUNDLES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_PRODUCT_TEMPLATES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_PAGE_PREVIEW_RELATIONSHIP_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_PRODUCT_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_PUBLICATION_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL };
    
    RELATIONSHIP_SIDE_1_LABELS = new String[] { ARTICLES_LABEL, MARKET_LABEL,
        CAMPAIGN_LABEL, CAMPAIGN_LABEL, TEXTASSET_LABEL, SUPPLIER_LABEL,
        PROMOTION_LABEL, ARTICLES_LABEL, ARTICLES_LABEL,
        MARKETING_PRODUCT_LABEL, MARKETING_BUNDLE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, STANDARD_DTP_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_LABEL, STANDARD_DTP_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL, STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL };
    
    RELATIONSHIP_SIDE_2_LABELS = new String[] { IMAGES, IMAGES, IMAGES, IMAGES, IMAGES,
        CAMPAIGN_LABEL, IMAGES, IMAGES, IMAGES, MARKET_LABEL, IMAGES,
        STANDARD_GOLDEN_ARTICLE_KLASS_LABEL, IMAGES, IMAGES, MARKET_LABEL, 
        IMAGES, IMAGES, IMAGES, MARKETING_PRODUCT_LABEL, MARKETING_BUNDLE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, PAGE_PREVIEWS, IMAGES,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_PRODUCT_TEMPLATE_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL, IMAGES, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL };
    
    IMAGES = "Images__fr_FR";
    STANDARD_SYSTEM = "Standard System__fr_FR";
    
    TAGS_LABELS = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        // status
        put("statustag", STATUS_TAG_LABEL);
        put("enrichmenttag", ENRICHMENT_TAG_LABEL);
        put("qualitychecktag", QUALITY_CHECK_TAG_LABEL);
        put("translationtag", TRANSLATION_TAG_LABEL);
        put("approvaltag", APPROVAL_TAG_LABEL);
        put("productivetag", PRODUCTIVE_TAG_LABEL);
        put("blockedfromplanning", BLOCKED_FROM_PLANNING_LABEL);
        
        // availability
        put("availabilitytag", AVAILABILITY_TAG_LABEL);
        put("onrequest", ON_REQUEST_LABEL);
        put("onstock", ON_STOCK_LABEL);
        put("regularlyavailable", REGULARLY_AVAILABLE_LABEL);
        put("dropshipping", DROP_SHIPPING_LABEL);
        
        // lagnguage tag 8
        /* put("languagetag",LANGUAGE_TAG_LABEL);
        put("english",ENGLISH_LABEL);
        put("german",GERMAN_LABEL);
        put("spanish",SPANISH_LABEL);
        put("italian",ITALIAN_LABEL);
        put("french",FRENCH_LABEL);
        put("portugese",PORTUGESE_LABEL);
        put("swedish",SWEDISH_LABEL);*/
        
        // life cylcel status tag 10
        put("lifestatustag", LIFE_STATUS_TAG_LABEL);
        put("life_status_inbox", LIFE_STATUS_INBOX_LABEL);
        put("life_status_nointerest", LIFE_STATUS_NO_INTEREST_LABEL);
        put("life_status_preparation", LIFE_STATUS_PREPARATION_LABEL);
        put("life_status_active", LIFE_STATUS_ACTIVE_LABEL);
        put("life_status_activeblocked", LIFE_STATUS_ACTIVE_BLOCKED_LABEL);
        put("life_status_activebanned", LIFE_STATUS_ACTIVE_BANNED_LABEL);
        put("life_status_retired", LIFE_STATUS_RETIRED_LABEL);
        put("life_status_archived", LIFE_STATUS_ARCHIVED_LABEL);
        put("life_status_deleted", LIFE_STATUS_DELETED_LABEL);
        
        // listing status tag 8
        put("listingstatustag", LISTING_STATUS_TAG_LABEL);
        put("listing_status_catlog", LISTING_STATUS_CATLOG_LABEL);
        put("listing_status_ignored", LISTING_STATUS_IGNORED_LABEL);
        put("listing_status_rejected", LISTING_STATUS_REJECTED_LABEL);
        put("listing_status_onboardingpool", LISTING_STATUS_ONBOARDING_POOL_LABEL);
        put("listing_status_recommended", LISTING_STATUS_RECOMMENDED_LABEL);
        put("listing_status_shadowassortment", LISTING_STATUS_SHADOW_ASSORTMENT_LABEL);
        put("listing_status_listed", LISTING_STATUS_LISTED_LABEL);
        
        // system status tag 8
        put("T_STATUS_SYSTEM", T_STATUS_SYSTEM_LABEL);
        put("T_STATUS_SYSTEM_NEW", T_STATUS_SYSTEM_NEU_LABEL);
        put("T_STATUS_SYSTEM_INACTIV", T_STATUS_SYSTEM_INAKTIV_LABEL);
        put("T_STATUS_SYSTEM_ACTIV", T_STATUS_SYSTEM_AKTIV_LABEL);
        put("T_STATUS_SYSTEM_ARCHIVED", T_STATUS_SYSTEM_ARCHIVIERT_LABEL);
        put("T_STATUS_SYSTEM_DELETED", T_STATUS_SYSTEM_GELOESCHT_LABEL);
        put("T_STATUS_SYSTEM_PREPARE", T_STATUS_SYSTEM_PREPARE_LABEL);
        put("T_STATUS_SYSTEM_BLOCKED", T_STATUS_SYSTEM_BLOCKED_LABEL);
        
        // project status 9
        
        put("T_STATUS_PROJECT", T_STATUS_PROJECT_LABEL);
        put("T_STATUS_PROJECT_IN_PLANNING", T_STATUS_PROJEKT_IN_PLANUNG);
        put("T_STATUS_PROJECT_CANCELED", T_STATUS_PROJEKT_ABGEBROCHEN);
        put("T_STATUS_PROJECT_COMPLETE", T_STATUS_PROJEKT_ABGESCHLOSSEN);
        put("T_STATUS_PROJECT_ERROR_PROCESSING", T_STATUS_PROJEKT_FEHLER_BEARBEITEN);
        put("T_STATUS_PROJECT_LICENSE_MISSING", T_STATUS_PROJEKT_LIZENZ_FEHLT);
        put("T_STATUS_PROJECT_QUALITY_CHECK", T_STATUS_PROJEKT_QUALITAT_SICHERN);
        // put("T_STATUS_PROJECT_USING_ALLOWED", T_STATUS_PROJEKT_VERWENDBAR);
        put("T_STATUS_PROJECT_REWORK", T_STATUS_PROJEKT_ZUR_UBERARBEITUNG);
        
        // campaign type tag 6
        put("T_CAMP_TYPE", T_CAMP_TYPE_LABEL);
        put("T_CAMP_TYPE_NATIONAL", T_CAMP_TYPE_NATIONAL_LABEL);
        put("T_CAMP_TYPE_REGIONAL", T_CAMP_TYPE_REGIONAL_LABEL);
        put("T_CAMP_TYPE_CATALINA", T_CAMP_TYPE_CATALINA_LABEL);
        put("T_CAMP_TYPE_DCARD", T_CAMP_TYPE_DCARD_LABEL);
        put("T_CAMP_TYPE_SUPPLIER", T_CAMP_TYPE_LIEFERANT_LABEL);
        
        // task status tag 8
        put("taskstatustag", TASK_STATUS_TAG_LABEL);
        put("taskplanned", PLANNED_LABEL);
        put("taskready", READY_LABEL);
        put("taskdeclined", DECLINED_LABEL);
        put("taskinprogress", IN_PROGRESS_LABEL);
        put("taskdone", DONE_LABEL);
        put("taskverified", VERIFIED_LABEL);
        put("tasksignedoff", SIGNED_OFF_LABEL);
        
        // resolution tag 4
        put("resolutiontag", RESOLUTION_TAG_LABEL);
        put("resolution_300P", RESOLUTION_300P_LABEL);
        put("resolution_150P", RESOLUTION_150P_LABEL);
        put("resolution_72P", RESOLUTION_72P_LABEL);
        
        put("imageextensiontag", IMAGE_EXTENSION_LABEL);
        put("image_extension_format_original", IMAGE_FORMAT_ORIGINAL_LABEL);
        put("image_extension_format_jpg", IMAGE_FORMAT_JPG_LABEL);
        put("image_extension_format_png", IMAGE_FORMAT_PNG_LABEL);
        
        // boolean tag 6
        put("isordertag", IS_ORDER_TAG_LABEL);
        put("isordertagvalue", IS_ORDER_TAG_LABEL);
        put("issalestag", IS_SALES_TAG_LABEL);
        put("issalestagvalue", IS_SALES_TAG_LABEL);
        put("isbaseunittag", IS_BASEUNIT_TAG_LABEL);
        put("isbaseunittagvalue", IS_BASEUNIT_TAG_LABEL);
        
        // suported languages
        /* put("supportedLanguages", SUPPORTED_LANGUAGES);
        put("en", EN);
        put("dr", DE);
        put("es", ES);
        put("fr", FR);
        
        put("language", LANGUAGE);
        put("en_US", EN_US);
        put("en_UK", EN_UK);
        put("de_DE", DE_DE);
        put("fr_FR", FR_FR);
        put("es_ES", ES_ES);*/
        
      }
    };
    
    Language_Labels = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        put(Constants.ENGLISH_US, ENGLISH_LABEL);
        put(Constants.FRENCH, FRENCH_LABEL);
        put(Constants.SPANISH, SPANISH_LABEL);
        put(Constants.GERMAN, GERMAN_LABEL);
      }
    };
    
    Tabs_Labels = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        put(SystemLevelIds.DEFAULT_DASHBOARD_TAB_ID, DEFAULT_DASHBOARD_TAB);
        put(SystemLevelIds.DEFAULT_DATA_INTEGRATION_TAB_ID, DEFAULT_DATA_INTEGRATION_TAB);
      }
    };
    
    // Smart Documents
    SMART_DOCUMENT_LABEL = "Smart Document__fr_FR";
    
    // References
    STANDARD_ARTICLE_SMART_DOCUMENT_REFRENCE_ID = "Article-Smart Document Reference__fr_FR";
    STANDARD_MARKETING_ARTICLE_SMART_DOCUMENT_REFRENCE_ID = "Marketing Article-Smart Document Reference__fr_FR";
    
    REFERENCE_LABELS = new String[] { STANDARD_ARTICLE_SMART_DOCUMENT_REFRENCE_ID,
        STANDARD_MARKETING_ARTICLE_SMART_DOCUMENT_REFRENCE_ID };
    
    REFERENCE_SIDE_1_LABELS = new String[] { ARTICLES_LABEL, MARKETING_PRODUCT_LABEL };
    
    REFERENCE_SIDE_2_LABELS = new String[] { SMART_DOCUMENT_LABEL, SMART_DOCUMENT_LABEL };
  }
}
