package com.cs.core.runtime.interactor.constants.projectspecific;

import java.util.HashMap;

import org.springframework.stereotype.Component;

import com.cs.constants.SystemLevelIds;
import com.cs.core.runtime.interactor.constants.application.Constants;

@Component
public class InitializeDataLabels__es_ES extends InitializeDataLabelKeys {
  
  public InitializeDataLabels__es_ES()
  {
    
    ASSET_COVERFLOW_ATTRIBUTE_LABEL = "File Preview__es_ES";
    ADDRESS_ATTRIBUTE_LABEL = "Address__es_ES";
    DESCRIPTION_ATTRIBUTE_LABEL = "Description__es_ES";
    DUE_DATE_ATTRIBUTE_LABEL = "Due Date__es_ES";
    FIRST_NAME_ATTRIBUTE_LABEL = "First Name__es_ES";
    LIST_PRICE_ATTRIBUTE_LABEL = "List Price__es_ES";
    LONG_DESCRIPTION_ATTRIBUTE_LABEL = "Long Description__es_ES";
    MINIMUM_PRICE_ATTRIBUTE_LABEL = "Minimum Price__es_ES";
    PID_ATTRIBUTE_LABEL = "PID__es_ES";
    PIN_CODE_ATTRIBUTE_LABEL = "Pin Code__es_ES";
    SELLING_PRICE_ATTRIBUTE_LABEL = "Selling Price__es_ES";
    SHORT_DESCRIPTION_ATTRIBUTE_LABEL = "Short Description__es_ES";
    SKU_ATTRIBUTE_LABEL = "SKU__es_ES";
    TELEPHONE_NUMBER_ATTRIBUTE_LABEL = "Telephone Number__es_ES";
    DISCOUNT_ATTRIBUTE_LABEL = "Discount (%)__es_ES";
    GTIN_ATTRIBUTE_LABEL = "GTIN__es_ES";
    LAST_NAME_ATTRIBUTE_LABEL = "Last Name__es_ES";
    MAXIMUM_PRICE_ATTRIBUTE_LABEL = "Maximum Price__es_ES";
    
    CREATED_BY_ATTRIBUTE = "Created By__es_ES";
    CREATED_ON_ATTRIBUTE = "Created On__es_ES";
    LAST_MODIFIED_ATTRIBUTE = "Last Modified__es_ES";
    LAST_MODIFIED_BY_ATTRIBUTE = "Last Modified By__es_ES";
    NAME_ATTRIBUTE = "Name__es_ES";
    
    DTP_ERROR_MARGIN_LABEL = "Error margin__es_ES";
    DTP_MAX_NO_OF_SLOTS_ATTRIBUTE_LABEL = "Maximum Number of Slots__es_ES";
    DTP_MINIMUM_SLOT_HEIGHT_ATTRIBUTE_LABEL = "Minimum Slot Height__es_ES";
    DTP_MINIMUM_SLOT_WIDTH_ATTRIBUTE_LABEL = "Minimum Slot Width__es_ES";
    DTP_DELTA_ATTRIBUTE_LABEL = "Delta__es_ES";
    
    I_META_FILE_NAME = "I_META_FILE_NAME__es_ES";
    I_META_DOCUMENT_TYPE = "I_META_DOCUMENT_TYPE__es_ES";
    I_APPLICATION = "I_APPLICATION__es_ES";
    I_CREATE_DATE = "I_CREATE_DATE__es_ES";
    I_MODIFICATION_DATE = "I_MODIFICATION_DATE__es_ES";
    I_META_FILE_SIZE = "I_META_FILE_SIZE__es_ES";
    I_DIMENSIONS = "I_DIMENSIONS__es_ES";
    I_DIMENSION_IN_INCH = "I_DIMENSION_IN_INCH__es_ES";
    I_RESOLUTION = "I_RESOLUTION__es_ES";
    I_BIT_DEPTH = "I_BIT_DEPTH__es_ES";
    I_COLOR_MODE = "I_COLOR_MODE__es_ES";
    I_COLOR_PROFILE = "I_COLOR_PROFILE__es_ES";
    I_META_CREATOR_AUTHOR = "I_META_CREATOR_AUTHOR__es_ES";
    I_META_CREATOR_STREET = "I_META_CREATOR_STREET__es_ES";
    I_META_CREATOR_LOCATION = "I_META_CREATOR_LOCATION__es_ES";
    I_META_CREATOR_STATE = "I_META_CREATOR_STATE__es_ES";
    I_META_CREATOR_POSTAL_CODE = "I_META_CREATOR_POSTAL_CODE__es_ES";
    I_META_CREATOR_COUNTRY = "I_META_CREATOR_COUNTRY__es_ES";
    I_META_CREATOR_TEL = "I_META_CREATOR_TEL__es_ES";
    I_META_CREATOR_EMAIL = "I_META_CREATOR_EMAIL__es_ES";
    I_META_CREATOR_WWW = "I_META_CREATOR_WWW__es_ES";
    I_META_HEADING = "I_META_HEADING__es_ES";
    I_META_DESCRIPTION = "I_META_DESCRIPTION__es_ES";
    I_META_KEYWORDS = "I_META_KEYWORDS__es_ES";
    I_META_LOCATION_DETAIL = "I_META_LOCATION_DETAIL__es_ES";
    I_META_LOCATION = "I_META_LOCATION__es_ES";
    I_META_STATE = "I_META_STATE__es_ES";
    I_META_COUNTRY = "I_META_COUNTRY__es_ES";
    I_META_TITEL = "I_META_TITEL__es_ES";
    I_META_COPYRIGHT = "I_META_COPYRIGHT__es_ES__es_ES";
    I_META_COPYRIGHT_STATUS = "I_META_COPYRIGHT_STATUS__es_ES";
    I_META_EXPOSURE_INDEX = "I_META_EXPOSURE_INDEX__es_ES";
    I_META_FOCAL_RANGE = "I_META_FOCAL_RANGE__es_ES";
    I_META_MAX_BLINDING_VALUE = "I_META_MAX_BLINDING_VALUE__es_ES";
    I_META_RECORDING_DATE = "I_META_RECORDING_DATE__es_ES";
    I_META_EXPOSURE_CONTROLS = "I_META_EXPOSURE_CONTROLS__es_ES";
    I_META_LIGHT_SOURCE = "I_META_LIGHT_SOURCE__es_ES";
    I_META_SENSOR_TYPE = "I_META_SENSOR_TYPE__es_ES";
    I_META_BRAND = "I_META_BRAND__es_ES";
    I_META_MODELL = "I_META_MODELL__es_ES";
    I_META_SERIAL_NUMBER = "I_META_SERIAL_NUMBER__es_ES";
    I_META_PIXEL_X_DIMENSION = "I_META_PIXEL_X_DIMENSION__es_ES";
    I_META_PIXEL_Y_DIMENSION = "I_META_PIXEL_Y_DIMENSION__es_ES";
    I_META_HIGH_RESOLUTION = "I_META_HIGH_RESOLUTION__es_ES";
    I_META_WIDTH_RESOLUTION = "I_META_WIDTH_RESOLUTION__es_ES";
    I_META_X_RESOLUTION = "I_META_X_RESOLUTION__es_ES";
    I_META_Y_RESOLUTION = "I_META_Y_RESOLUTION__es_ES";
    
    // Tags
    IS_ORDER_TAG_LABEL = "isOrder__es_ES";
    IS_SALES_TAG_LABEL = "isSales__es_ES";
    IS_BASEUNIT_TAG_LABEL = "isBaseUnit__es_ES";
    
    LISTING_STATUS_TAG_LABEL = "Listing Status__es_ES";
    LISTING_STATUS_CATLOG_LABEL = "Catalog__es_ES";
    LISTING_STATUS_IGNORED_LABEL = "Ignored__es_ES";
    LISTING_STATUS_REJECTED_LABEL = "Rejected__es_ES";
    LISTING_STATUS_ONBOARDING_POOL_LABEL = "Onboarding Pool__es_ES";
    LISTING_STATUS_RECOMMENDED_LABEL = "Recommended__es_ES";
    LISTING_STATUS_SHADOW_ASSORTMENT_LABEL = "Shadow Assortment__es_ES";
    LISTING_STATUS_LISTED_LABEL = "Listed__es_ES";
    LIFE_STATUS_TAG_LABEL = "Life Cycle Status__es_ES";
    LIFE_STATUS_INBOX_LABEL = "Inbox__es_ES";
    LIFE_STATUS_NO_INTEREST_LABEL = "No Interest__es_ES";
    LIFE_STATUS_PREPARATION_LABEL = "Preparation__es_ES";
    LIFE_STATUS_ACTIVE_LABEL = "Active__es_ES";
    LIFE_STATUS_ACTIVE_BLOCKED_LABEL = "Active - Blocked__es_ES";
    LIFE_STATUS_ACTIVE_BANNED_LABEL = "Active - Banned__es_ES";
    LIFE_STATUS_RETIRED_LABEL = "Retired__es_ES";
    LIFE_STATUS_ARCHIVED_LABEL = "Archived__es_ES";
    LIFE_STATUS_DELETED_LABEL = "Deleted__es_ES";
    STATUS_TAG_LABEL = "Status__es_ES";
    ENRICHMENT_TAG_LABEL = "Enrichment__es_ES";
    QUALITY_CHECK_TAG_LABEL = "Quality Check__es_ES";
    TRANSLATION_TAG_LABEL = "Translation__es_ES";
    APPROVAL_TAG_LABEL = "Approval__es_ES";
    PRODUCTIVE_TAG_LABEL = "Productive__es_ES";
    BLOCKED_FROM_PLANNING_LABEL = "Blocked from planning__es_ES";
    AVAILABILITY_TAG_LABEL = "Availability__es_ES";
    ON_REQUEST_LABEL = "On Request__es_ES";
    ON_STOCK_LABEL = "On Stock__es_ES";
    REGULARLY_AVAILABLE_LABEL = "Regularly Available__es_ES";
    DROP_SHIPPING_LABEL = "Drop Shipping__es_ES";
    LANGUAGE_TAG_LABEL = "Language__es_ES";
    ENGLISH_LABEL = "Inglés";
    GERMAN_LABEL = "Alemán";
    SPANISH_LABEL = "Español";
    ITALIAN_LABEL = "Italian__es_ES";
    FRENCH_LABEL = "Francés";
    PORTUGESE_LABEL = "Portugese__es_ES";
    SWEDISH_LABEL = "Swedish__es_ES";
    
    SUPPORTED_LANGUAGES = "SupportedLanguages__es_ES";
    EN = "en__es_ES";
    DE = "de__es_ES";
    FR = "fr__es_ES";
    ES = "es__es_ES";
    
    LANGUAGE = "language__es_ES";
    EN_US = "English (U.S)__es_ES";
    EN_UK = "English (U.K)__es_ES";
    DE_DE = "Deutsch__es_ES";
    FR_FR = "Fran�ais__es_ES";
    ES_ES = "Espa�ol__es_ES";
    
    DEFAULT_DATA_INTEGRATION_TAB = "DefaultDataIntegrationTab__es_ES";
    DEFAULT_DASHBOARD_TAB = "DefaultDashboardTab__es_ES";
    
    T_STATUS_SYSTEM_LABEL = "Status__es_ES";
    T_STATUS_SYSTEM_NEU_LABEL = "Neu__es_ES";
    T_STATUS_SYSTEM_INAKTIV_LABEL = "Inaktiv__es_ES";
    T_STATUS_SYSTEM_AKTIV_LABEL = "Aktiv__es_ES";
    T_STATUS_SYSTEM_ARCHIVIERT_LABEL = "Archiviert__es_ES";
    T_STATUS_SYSTEM_GELOESCHT_LABEL = "GelÃ¶scht__es_ES";
    T_STATUS_SYSTEM_PREPARE_LABEL = "Vorbereitung__es_ES";
    T_STATUS_SYSTEM_BLOCKED_LABEL = "Gesperrt__es_ES";
    T_STATUS_PROJECT_LABEL = "Projektstatus__es_ES";
    
    T_CAMPAIGN_GOALS_LABEL = "Goals__es_ES";
    T_GOALS_BRAND_PROMOTION_LABEL = "Brand Promotion__es_ES";
    T_GOALS_SEASONAL_PROMOTION_LABEL = "Seasonal Promotion__es_ES";
    T_GOALS_NEW_ARRIVALS_LABEL = "New Arrivals__es_ES";
    T_GOALS_PROMOTION_HIGH_MARGIN_LABEL = "Promotion of Higher Margin Products__es_ES";
    T_GOALS_INVENTORY_CLEARANCE_LABEL = "Inventory Clearance__es_ES";
    T_GOALS_LOYALTY_POINTS_LABEL = "Niche group promotion (Loyalty Points)__es_ES";
    T_GOALS_SPECIAL_TOPIC_LABEL = "Special topic promotion__es_ES";
    T_GOALS_ACQUIRE_NEW_CUSTOMERS_LABEL = "Acquire new customers__es_ES";
    T_GOALS_RETAIN_EXISTING_CUSTOMERS_LABEL = "Retain existing customers__es_ES";
    
    T_CAMP_TYPE_LABEL = "Kampagnen-Typ__es_ES";
    T_CAMP_TYPE_NATIONAL_LABEL = "National__es_ES";
    T_CAMP_TYPE_REGIONAL_LABEL = "Regional__es_ES";
    T_CAMP_TYPE_CATALINA_LABEL = "Catalina__es_ES";
    T_CAMP_TYPE_DCARD_LABEL = "DeutschlandCard__es_ES";
    T_CAMP_TYPE_LIEFERANT_LABEL = "Lieferant__es_ES";
    TASK_STATUS_TAG_LABEL = "Task-Status__es_ES";
    PLANNED_LABEL = "Planned__es_ES";
    READY_LABEL = "Ready__es_ES";
    DECLINED_LABEL = "Declined__es_ES";
    IN_PROGRESS_LABEL = "In_Progress__es_ES";
    DONE_LABEL = "Done__es_ES";
    VERIFIED_LABEL = "Verified__es_ES";
    SIGNED_OFF_LABEL = "Signed_Off__es_ES";
    
    RESOLUTION_TAG_LABEL = "Resolution__es_ES";
    RESOLUTION_300P_LABEL = "300_dpi__es_ES";
    RESOLUTION_150P_LABEL = "150_dpi__es_ES";
    RESOLUTION_72P_LABEL = "72_dpi__es_ES";
    IMAGE_EXTENSION_LABEL = "Image Extension__es_ES";
    IMAGE_FORMAT_JPG_LABEL = "jpg__es_ES";
    IMAGE_FORMAT_PNG_LABEL = "png__es_ES";
    IMAGE_FORMAT_ORIGINAL_LABEL = "original__es_ES";
    
    T_STATUS_PROJEKT_VERWENDBAR = "Verwendbar";
    T_STATUS_PROJEKT_IN_PLANUNG = "In Planung";
    T_STATUS_PROJEKT_ABGESCHLOSSEN = "abgeschlossen";
    T_STATUS_PROJEKT_ZUR_UBERARBEITUNG = "zur Ãœberarbeitung";
    T_STATUS_PROJEKT_QUALITAT_SICHERN = "QualitÃ¤t sichern";
    T_STATUS_PROJEKT_FEHLER_BEARBEITEN = "Fehler bearbeiten";
    T_STATUS_PROJEKT_LIZENZ_FEHLT = "Lizenz fehlt";
    T_STATUS_PROJEKT_ABGEBROCHEN = "abgebrochen";
    
    CREATED_EVENT_LABEL = "Created__es_ES";
    
    LANGUAGE_TAXONOMY_LABEL = "Language__es_ES";
    
    PRICING_PROPERTY_COLLECTION_LABEL = "Pricing__es_ES";
    ARTICLE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "General Information__es_ES";
    MARKET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Market General Information__es_ES";
    ASSET_GENERAL_INFORMATION_PROPERTY_COLLETION_LABEL = "Asset Information__es_ES";
    CAMPAIGN_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "General Information__es_ES";
    PROMOTION_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Promotion General Information__es_ES";
    SUPPLIER_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Supplier General Information__es_ES";
    TEXTASSET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Text-Asset General Information__es_ES";
    DEFAULT_X_RAY_PROPERTY_COLLECTION_LABEL = "Default X-Ray Collection__es_ES";
    METADATA_COLLECTION_LABEL = "Metadata__es_ES";
    UNIT_DEFAULT_PROPERTYCOLLECTION_LABEL = "Unit Information__es_ES";
    DTP_TEMPLATE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Template General Information__es_ES";
    DTP_DOCUMENT_TEMPLATE_INFORMATION_PROPERTY_COLLECTION_LABEL = "Document Template Information__es_ES";
    DTP_TEMPLATE_FILE_INFOMATION_PROPERTY_COLLECTION_LABEL = "Template File Information__es_ES";
    
    STANDARD_ARTICLE_KLASS_LABEL = "Article__es_ES";
    STANDARD_SET_KLASS_LABEL = "Set__es_ES";
    STANDARD_COLLETION_KLASS_LABEL = "Collection__es_ES";
    STANDARD_CHANNEL_CLASSES_LABEL = "Channel Classes__es_ES";
    STANDARD_PRODUCT_TYPES_LABEL = "Product Types__es_ES";
    STANDARD_SINGLE_ARTICLE = "Single Article__es_ES";
    STANDARD_ATTRIBUTION_CLASSES_LABEL = "Attribution Classes__es_ES";
    STANDARD_FILE_KLASS_LABEL = "Archivo";
    STANDARD_VERSION_KLASS_LABEL = "Version Class__es_ES";
    STANDARD_GOLDEN_ARTICLE_KLASS_LABEL = "Golden Article__es_ES";
    
    STANDARD_VIDEO_KLASS_LABEL = "Video__es_ES";
    STANDARD_DOCUMENT_KLASS_LABEL = "Document__es_ES";
    STANDARD_IMAGE_KLASS_LABEL = "Image__es_ES";
    STANDARD_ATTACHMENT_KLASS_LABEL = "Attachment__es_ES";
    STANDARD_ASSET_KLASS_LABEL = "Asset_es_ES";
    STANDARD_SMARTDOCUMENT_KLASS_LABEL = "Smart Document__es_ES";
    
    STANDARD_CAMPAIGN_KLASS_LABEL = "Campaign__es_ES";
    
    STANDARD_PROPERTY_COLLECTION_TAB_LABEL = "Properties__es_ES";
    STANDARD_RELATIONSHIP_TAB_LABEL = "Relationships__es_ES";
    STANDARD_CONTEXT_TAB_LABEL = "Contexts__es_ES";
    STANDARD_TASK_TAB_LABEL = "Tasks__es_ES";
    STANDARD_TIMELINE_TAB_LABEL = "Timeline__es_ES";
    STANDARD_RENDITION_TAB_LABEL = "Renditions__es_ES";
    STANDARD_OVERVIEW_TAB_LABEL = "Overview__es_ES";
    STANDARD_MDM_TAB_LABEL = "Mdm__es_ES";
    
    MARKETING_PRODUCT_LABEL = "Marketing Product__es_ES";
    MARKETING_BUNDLE_LABEL = "Marketing Bundle__es_ES";    
    PROMOTION_LABEL = "Promotion__es_ES";
    SUPPLIER_LABEL = "Supplier__es_ES";
    MARKET_LABEL = "Target_es";
    
    STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL = "PublicationTemplate__es_ES";
    STANDARD_DTP_PUBLICATION_LABEL = "Publication__es_ES";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL = "DocumentTemplate__es_ES";
    STANDARD_DTP_PRODUCT_TEMPLATE_LABEL = "ProductTemplate__es_ES";
    STANDARD_DTP_ABSTRACT_DOCUMENT_TEMPLATE_LABEL = "Abstract Document Template__es_ES";
    STANDARD_DTP_ABSTRACT_PRODUCT_TEMPLATE_LABEL = "Abstract Product Template__es_ES";
    STANDARD_DTP_ABSTRACT_PUBLICATION_TEMPLATE_LABEL = "Abstract Publication Template__es_ES";
    STANDARD_DTP_ABSTRACT_PUBLICATION_LABEL = "Abstract Publication__es_ES";
    STANDARD_DTP_ABSTRACT_DOCUMENT_LABEL = "Abstract Document__es_ES";
    STANDARD_DTP_DOCUMENT_LABEL = "Document__es_ES";
    STANDARD_DTP_DOCUMENT_VARIANT_LABEL = "Document Variant__es_ES";
    
    ADMIN_LABEL = "admin__es_ES";
    
    SUPPLIERS_LABEL = "Supplier__es_ES";
    MARKETPLACES_LABEL = "Marketplaces__es_ES";
    DISTRIBUTORS_LABEL = "Distributors__es_ES";
    WHOLESALERS_LABEL = "Wholesalers__es_ES";
    TRANSLATION_AGENCY_LABEL = "Translation Agency__es_ES";
    CONTENT_ENRICHMENT_AGENCY_LABEL = "Content Enrichment Agency__es_ES";
    DIGITAL_ASSET_AGENCY_LABEL = "Digital Asset Agency__es_ES";
    
    // Role
    RESPONSIBLE_ROLE_LABEL = "Responsible__es_ES";
    ACCOUNTABLE_ROLE_LABEL = "Accountable__es_ES";
    CONSULTED_ROLE_LABEL = "Consulted__es_ES";
    INFORMED_ROLE_LABEL = "Informed__es_ES";
    VERIFY_ROLE_LABEL = "Verify__es_ES";
    SIGNOFF_ROLE_LABEL = "Sign-off__es_ES";
    ADMIN_ROLE_LABEL = "Admin__es_ES";
    
    RACIVS_ROLE_LABELS = new String[] { RESPONSIBLE_ROLE_LABEL, ACCOUNTABLE_ROLE_LABEL,
        CONSULTED_ROLE_LABEL, INFORMED_ROLE_LABEL, VERIFY_ROLE_LABEL, SIGNOFF_ROLE_LABEL,
        ADMIN_ROLE_LABEL };
    
    APPROVER_ROLE_LABEL = "Approver(Sign-Off)__es_ES";
    OWNER_ROLE_LABEL = "Owner(Responsible)__es_ES";
    SUBSCRIBER_ROLE_LABEL = "Subscriber(Informed)__es_ES";
    CONTRIBUTOR_ROLE_LABEL = "Contributor(Consulted)__es_ES";
    REVIEWER_ROLE_LABEL = "Reviewer(Verify)__es_ES";
    SENIOR_MANAGER_ROLE_LABEL = "Senior Manager(Accountable)__es_ES";
    ASSIGNEE_ROLE_LABEL = "Assignee__es_ES";
    
    STANDARD_ARTICLE_ASSET_RELATIONSHIP_LABEL = "Article-Asset Relationship__es_ES";
    STANDARD_MARKET_ASSET_RELATIONSHIP_LABEL = "Market-Asset Relationship__es_ES";
    STANDARD_CAMPAIGN_ASSET_RELATIONSHIP_LABEL = "Campaign-Asset Relationship__es_ES";
    STANDARD_CAMPAIGN_CAMPAIGN_RELATIONSHIP_LABEL = "Campaign-Campaign Relationship__es_ES";
    STANDARD_TEXTASSET_ASSET_RELATIONSHIP_LABEL = "TextAsset-Asset Relationship__es_ES";
    STANDARD_SUPPLIER_ASSET_RELATIONSHIP_LABEL = "Supplier-Asset Relationship__es_ES";
    STANDARD_PROMOTION_ASSET_RELATIONSHIP_LABEL = "Promotion-Asset Relationship__es_ES";
    STANDARD_ARTICLE_MARKET_RELATIONSHIP_LABEL = "Artikel MÃ¤rkte__es_ESS";
    STANDARD_ARTICLE_GOLDEN_ARTICLE_RELATIONSHIP_LABEL = "Article-GoldenArticle Relationship__es_ES";
    STANDARD_ARTICLE_MARKETING_ARTICLE_RELATIONSHIP_LABEL = "Article-MarketingArticle Relationship__es_ES";
    
    STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_LABEL = "PublicationTemplate - DocumentTemplate Relationship__es_ES";
    STANDARD_DTP_PRODUCT_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "Product Template - Asset Relationship__es_ES";
    STANDARD_DTP_PUBLICATION_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "Publication Template - Asset Relationship__es_ES";
    STANDARD_DTP_DOCUMENT_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "DocumentTemplate - Asset Relationship__es_ES";
    STANDARD_DTP_DOCUMENT_TEMPLATE_PAGE_PREVIEW_RELATIONSHIP_LABEL = "DocumentTemplate - Page Preview Relationship__es_ES";
    STANDARD_DTP_PUBLICATION_DTP_PUBLICATION_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Publication Template__es_ES";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_ARTICLES_RELATIONSHIP_LABEL = "DocumentTemplate - Marketing Articles Relationship__es_ES";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_PRODUCT_TEMPLATES_RELATIONSHIP_LABEL = "DocumentTemplate - Product Template Relationship__es_ES";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_BUNDLE_RELATIONSHIP_LABEL = "DocumentTemplate - Marketing Bundle Relationship__es_ES";
    STANDARD_DTP_PUBLICATION_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Document Template__es_ES";
    STANDARD_DTP_PUBLICATION_DTP_PRODUCT_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Product Template__es_ES";
    STANDARD_MARKETING_ARTICLE_ASSET_RELATIONSHIP_LABEL = "MarketingArticle - Asset Relationship__es_ES";
    STANDARD_MARKETING_BUNDLE_ASSET_RELATIONSHIP_LABEL = "MarketingBundle - Asset Relationship__es_ES";
    
    PAGE_PREVIEWS = "Page Previews__es_ES";
    
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_ARTICLES_RELATIONSHIP_LABEL = "Document Template - Marketing Article__es_ES";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_BUNDLES_RELATIONSHIP_LABEL = "Document Template - Marketing Bundle__es_ES";
    STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL = "Publication Template - Document Template__es_ES";
    
    // _LABEL = "side 1__es_ES" ;
    ARTICLES_LABEL = "Articles__es_ES";
    TARGETS_LABEL = "Targets__es_ES";
    CAMPAIGN_LABEL = "Campaign__es_ES";
    TEXTASSET_LABEL = "TextAsset__es_ES";
    SUPPLIER_LABEL = "Supplier__es_ES";
    PROMOTION_LABEL = "Promotion__es_ES";
    
    IMAGES = "Images__es_ES";
    
    STANDARD_OVERVIEW_TAB_LABEL = "overview_tab__es_ES";
    STANDARD_PROPERTY_COLLECTION_TAB_LABEL = "property_collection_tab__es_ES";
    STANDARD_RELATIONSHIP_TAB_LABEL = "relationship_tab__es_ES";
    STANDARD_CONTEXT_TAB_LABEL = "context_tab__es_ES";
    STANDARD_TASK_TAB_LABEL = "task_tab__es_ES";
    STANDARD_TIMELINE_TAB_LABEL = "timeline_tab__es_ES";
    STANDARD_RENDITION_TAB_LABEL = "renditions_tab__es_ES";
    STANDARD_CONFIGURATION_TAB_LABEL = "configurations_tab__es_ES";
    STANDARD_MDM_TAB_LABEL = "mdm_tab__es_ES";
    STANDARD_DUPLICATE_TAB_LABEL = "duplicates_tab__es_ES";
    
    STANDARD_TAB_LABELS = new String[] { STANDARD_OVERVIEW_TAB_LABEL,
        STANDARD_PROPERTY_COLLECTION_TAB_LABEL, STANDARD_RELATIONSHIP_TAB_LABEL,
        STANDARD_CONTEXT_TAB_LABEL, STANDARD_TASK_TAB_LABEL, 
        STANDARD_TIMELINE_TAB_LABEL, STANDARD_RENDITION_TAB_LABEL,
        STANDARD_CONFIGURATION_TAB_LABEL, STANDARD_MDM_TAB_LABEL, STANDARD_DUPLICATE_TAB_LABEL };
    
    DTP_KLASS_LABELS = new String[] { STANDARD_DTP_ABSTRACT_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_ABSTRACT_PRODUCT_TEMPLATE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, STANDARD_DTP_ABSTRACT_PUBLICATION_TEMPLATE_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL };
    
    DTP_PUBLICATION_LABELS = new String[] { STANDARD_DTP_ABSTRACT_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_LABEL };
    
    DTP_DOCUMENT_LABELS = new String[] { STANDARD_DTP_ABSTRACT_DOCUMENT_LABEL,
        STANDARD_DTP_DOCUMENT_LABEL, STANDARD_DTP_DOCUMENT_VARIANT_LABEL };
    
    STANDARD_ORGANIZATION = "Standard Organization__es_ES";
    
    ATTRIBUTE_LABELS = new String[] { ASSET_COVERFLOW_ATTRIBUTE_LABEL, ADDRESS_ATTRIBUTE_LABEL,
        DESCRIPTION_ATTRIBUTE_LABEL, DUE_DATE_ATTRIBUTE_LABEL, FIRST_NAME_ATTRIBUTE_LABEL,
        LIST_PRICE_ATTRIBUTE_LABEL, LONG_DESCRIPTION_ATTRIBUTE_LABEL, MINIMUM_PRICE_ATTRIBUTE_LABEL,
        PID_ATTRIBUTE_LABEL, PIN_CODE_ATTRIBUTE_LABEL, SELLING_PRICE_ATTRIBUTE_LABEL,
        SHORT_DESCRIPTION_ATTRIBUTE_LABEL, SKU_ATTRIBUTE_LABEL, TELEPHONE_NUMBER_ATTRIBUTE_LABEL,
        DISCOUNT_ATTRIBUTE_LABEL, GTIN_ATTRIBUTE_LABEL, LAST_NAME_ATTRIBUTE_LABEL,
        MAXIMUM_PRICE_ATTRIBUTE_LABEL, CREATED_BY_ATTRIBUTE, CREATED_ON_ATTRIBUTE,
        LAST_MODIFIED_ATTRIBUTE, LAST_MODIFIED_BY_ATTRIBUTE, NAME_ATTRIBUTE,
        DTP_MAX_NO_OF_SLOTS_ATTRIBUTE_LABEL, DTP_MINIMUM_SLOT_WIDTH_ATTRIBUTE_LABEL,
        DTP_MINIMUM_SLOT_HEIGHT_ATTRIBUTE_LABEL, DTP_ERROR_MARGIN_LABEL,
        DTP_DELTA_ATTRIBUTE_LABEL };
    
    METADATA_ATTRIBUTES_LABELS = new String[] { I_META_FILE_NAME, I_META_DOCUMENT_TYPE,
        I_APPLICATION, I_CREATE_DATE, I_MODIFICATION_DATE, I_META_FILE_SIZE, I_DIMENSIONS,
        I_DIMENSION_IN_INCH, I_RESOLUTION, I_BIT_DEPTH, I_COLOR_MODE, I_COLOR_PROFILE,
        I_META_CREATOR_AUTHOR, I_META_CREATOR_STREET, I_META_CREATOR_LOCATION, I_META_CREATOR_STATE,
        I_META_CREATOR_POSTAL_CODE, I_META_CREATOR_COUNTRY, I_META_CREATOR_TEL,
        I_META_CREATOR_EMAIL, I_META_CREATOR_WWW, I_META_HEADING, I_META_DESCRIPTION,
        I_META_KEYWORDS, I_META_LOCATION_DETAIL, I_META_LOCATION, I_META_STATE, I_META_COUNTRY,
        I_META_TITEL, I_META_COPYRIGHT, I_META_COPYRIGHT_STATUS, I_META_EXPOSURE_INDEX,
        I_META_FOCAL_RANGE, I_META_MAX_BLINDING_VALUE, I_META_RECORDING_DATE,
        I_META_EXPOSURE_CONTROLS, I_META_LIGHT_SOURCE, I_META_SENSOR_TYPE, I_META_BRAND,
        I_META_MODELL, I_META_SERIAL_NUMBER, I_META_PIXEL_X_DIMENSION, I_META_PIXEL_Y_DIMENSION,
        I_META_HIGH_RESOLUTION, I_META_WIDTH_RESOLUTION, I_META_X_RESOLUTION, I_META_Y_RESOLUTION };
    
    TAG_LABELS = new String[] { LISTING_STATUS_TAG_LABEL, LISTING_STATUS_CATLOG_LABEL,
        LISTING_STATUS_IGNORED_LABEL, LISTING_STATUS_REJECTED_LABEL,
        LISTING_STATUS_ONBOARDING_POOL_LABEL, LISTING_STATUS_RECOMMENDED_LABEL,
        LISTING_STATUS_SHADOW_ASSORTMENT_LABEL, LISTING_STATUS_LISTED_LABEL, LIFE_STATUS_TAG_LABEL,
        LIFE_STATUS_INBOX_LABEL, LIFE_STATUS_NO_INTEREST_LABEL, LIFE_STATUS_PREPARATION_LABEL,
        LIFE_STATUS_ACTIVE_LABEL, LIFE_STATUS_ACTIVE_BLOCKED_LABEL, LIFE_STATUS_ACTIVE_BANNED_LABEL,
        LIFE_STATUS_RETIRED_LABEL, LIFE_STATUS_ARCHIVED_LABEL, LIFE_STATUS_DELETED_LABEL,
        STATUS_TAG_LABEL, ENRICHMENT_TAG_LABEL, QUALITY_CHECK_TAG_LABEL, TRANSLATION_TAG_LABEL,
        APPROVAL_TAG_LABEL, PRODUCTIVE_TAG_LABEL, BLOCKED_FROM_PLANNING_LABEL,
        AVAILABILITY_TAG_LABEL, ON_REQUEST_LABEL, ON_STOCK_LABEL, REGULARLY_AVAILABLE_LABEL,
        DROP_SHIPPING_LABEL, LANGUAGE_TAG_LABEL, ENGLISH_LABEL, GERMAN_LABEL, SPANISH_LABEL,
        ITALIAN_LABEL, FRENCH_LABEL, PORTUGESE_LABEL, SWEDISH_LABEL };
    
    PROPERTY_COLLECTION_LABELS = new String[] { PRICING_PROPERTY_COLLECTION_LABEL,
        ARTICLE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        MARKET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        ASSET_GENERAL_INFORMATION_PROPERTY_COLLETION_LABEL,
        CAMPAIGN_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        PROMOTION_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        SUPPLIER_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        TEXTASSET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DEFAULT_X_RAY_PROPERTY_COLLECTION_LABEL, METADATA_COLLECTION_LABEL,
        UNIT_DEFAULT_PROPERTYCOLLECTION_LABEL,
        DTP_TEMPLATE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DTP_DOCUMENT_TEMPLATE_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DTP_TEMPLATE_FILE_INFOMATION_PROPERTY_COLLECTION_LABEL };
    
    TARGET_KLASS_LABELS = new String[] { MARKET_LABEL };
    
    PIM_KLASS_LABELS = new String[] { STANDARD_ARTICLE_KLASS_LABEL, STANDARD_PRODUCT_TYPES_LABEL,
        STANDARD_CHANNEL_CLASSES_LABEL, STANDARD_ATTRIBUTION_CLASSES_LABEL, STANDARD_SINGLE_ARTICLE,
        STANDARD_FILE_KLASS_LABEL, STANDARD_VERSION_KLASS_LABEL,
        STANDARD_GOLDEN_ARTICLE_KLASS_LABEL };
    
    MAM_KLASS_LABELS = new String[] { STANDARD_ATTACHMENT_KLASS_LABEL, STANDARD_ASSET_KLASS_LABEL,
        STANDARD_IMAGE_KLASS_LABEL, STANDARD_VIDEO_KLASS_LABEL, STANDARD_DOCUMENT_KLASS_LABEL,
        STANDARD_SMARTDOCUMENT_KLASS_LABEL };
    
    ROLES = new String[] { APPROVER_ROLE_LABEL, OWNER_ROLE_LABEL, SUBSCRIBER_ROLE_LABEL,
        CONTRIBUTOR_ROLE_LABEL, REVIEWER_ROLE_LABEL, SENIOR_MANAGER_ROLE_LABEL,
        ASSIGNEE_ROLE_LABEL };
    
    RELATIONSHIP_LABELS = new String[] { STANDARD_ARTICLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_MARKET_ASSET_RELATIONSHIP_LABEL, STANDARD_CAMPAIGN_ASSET_RELATIONSHIP_LABEL,
        STANDARD_CAMPAIGN_CAMPAIGN_RELATIONSHIP_LABEL, STANDARD_TEXTASSET_ASSET_RELATIONSHIP_LABEL,
        STANDARD_SUPPLIER_ASSET_RELATIONSHIP_LABEL, STANDARD_PROMOTION_ASSET_RELATIONSHIP_LABEL,
        STANDARD_ARTICLE_MARKET_RELATIONSHIP_LABEL,
        STANDARD_ARTICLE_GOLDEN_ARTICLE_RELATIONSHIP_LABEL,
        STANDARD_MARKETING_ARTICLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_MARKETING_BUNDLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_ARTICLES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_BUNDLES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_PRODUCT_TEMPLATES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_PAGE_PREVIEW_RELATIONSHIP_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_PRODUCT_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_PUBLICATION_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL };
    
    RELATIONSHIP_SIDE_1_LABELS = new String[] { ARTICLES_LABEL, MARKET_LABEL,
        CAMPAIGN_LABEL, CAMPAIGN_LABEL, TEXTASSET_LABEL, SUPPLIER_LABEL,
        PROMOTION_LABEL, ARTICLES_LABEL, ARTICLES_LABEL,
        MARKETING_PRODUCT_LABEL, MARKETING_BUNDLE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, STANDARD_DTP_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_LABEL, STANDARD_DTP_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL, STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL };
    
    RELATIONSHIP_SIDE_2_LABELS = new String[] { IMAGES, IMAGES, IMAGES, IMAGES, IMAGES,
        CAMPAIGN_LABEL, IMAGES, IMAGES, IMAGES, MARKET_LABEL, IMAGES,
        STANDARD_GOLDEN_ARTICLE_KLASS_LABEL, IMAGES, IMAGES, MARKET_LABEL,
        IMAGES, IMAGES, IMAGES, MARKETING_PRODUCT_LABEL, MARKETING_BUNDLE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, PAGE_PREVIEWS, IMAGES,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_PRODUCT_TEMPLATE_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL, IMAGES, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL };
    
    IMAGES = "Images__es_ES";
    STANDARD_SYSTEM = "Standard System__ens_ES";
    
    TAGS_LABELS = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        // status
        put("statustag", STATUS_TAG_LABEL);
        put("enrichmenttag", ENRICHMENT_TAG_LABEL);
        put("qualitychecktag", QUALITY_CHECK_TAG_LABEL);
        put("translationtag", TRANSLATION_TAG_LABEL);
        put("approvaltag", APPROVAL_TAG_LABEL);
        put("productivetag", PRODUCTIVE_TAG_LABEL);
        put("blockedfromplanning", BLOCKED_FROM_PLANNING_LABEL);
        
        // availability
        put("availabilitytag", AVAILABILITY_TAG_LABEL);
        put("onrequest", ON_REQUEST_LABEL);
        put("onstock", ON_STOCK_LABEL);
        put("regularlyavailable", REGULARLY_AVAILABLE_LABEL);
        put("dropshipping", DROP_SHIPPING_LABEL);
        
        // lagnguage tag 8
        /*put("languagetag",LANGUAGE_TAG_LABEL);
        put("english",ENGLISH_LABEL);
        put("german",GERMAN_LABEL);
        put("spanish",SPANISH_LABEL);
        put("italian",ITALIAN_LABEL);
        put("french",FRENCH_LABEL);
        put("portugese",PORTUGESE_LABEL);
        put("swedish",SWEDISH_LABEL);*/
        
        // life cylcel status tag 10
        put("lifestatustag", LIFE_STATUS_TAG_LABEL);
        put("life_status_inbox", LIFE_STATUS_INBOX_LABEL);
        put("life_status_nointerest", LIFE_STATUS_NO_INTEREST_LABEL);
        put("life_status_preparation", LIFE_STATUS_PREPARATION_LABEL);
        put("life_status_active", LIFE_STATUS_ACTIVE_LABEL);
        put("life_status_activeblocked", LIFE_STATUS_ACTIVE_BLOCKED_LABEL);
        put("life_status_activebanned", LIFE_STATUS_ACTIVE_BANNED_LABEL);
        put("life_status_retired", LIFE_STATUS_RETIRED_LABEL);
        put("life_status_archived", LIFE_STATUS_ARCHIVED_LABEL);
        put("life_status_deleted", LIFE_STATUS_DELETED_LABEL);
        
        // listing status tag 8
        put("listingstatustag", LISTING_STATUS_TAG_LABEL);
        put("listing_status_catlog", LISTING_STATUS_CATLOG_LABEL);
        put("listing_status_ignored", LISTING_STATUS_IGNORED_LABEL);
        put("listing_status_rejected", LISTING_STATUS_REJECTED_LABEL);
        put("listing_status_onboardingpool", LISTING_STATUS_ONBOARDING_POOL_LABEL);
        put("listing_status_recommended", LISTING_STATUS_RECOMMENDED_LABEL);
        put("listing_status_shadowassortment", LISTING_STATUS_SHADOW_ASSORTMENT_LABEL);
        put("listing_status_listed", LISTING_STATUS_LISTED_LABEL);
        
        // system status tag 8
        put("T_STATUS_SYSTEM", T_STATUS_SYSTEM_LABEL);
        put("T_STATUS_SYSTEM_NEW", T_STATUS_SYSTEM_NEU_LABEL);
        put("T_STATUS_SYSTEM_INACTIV", T_STATUS_SYSTEM_INAKTIV_LABEL);
        put("T_STATUS_SYSTEM_ACTIV", T_STATUS_SYSTEM_AKTIV_LABEL);
        put("T_STATUS_SYSTEM_ARCHIVED", T_STATUS_SYSTEM_ARCHIVIERT_LABEL);
        put("T_STATUS_SYSTEM_DELETED", T_STATUS_SYSTEM_GELOESCHT_LABEL);
        put("T_STATUS_SYSTEM_PREPARE", T_STATUS_SYSTEM_PREPARE_LABEL);
        put("T_STATUS_SYSTEM_BLOCKED", T_STATUS_SYSTEM_BLOCKED_LABEL);
        
        // project status 9
        
        put("T_STATUS_PROJECT", T_STATUS_PROJECT_LABEL);
        put("T_STATUS_PROJECT_IN_PLANNING", T_STATUS_PROJEKT_IN_PLANUNG);
        put("T_STATUS_PROJECT_CANCELED", T_STATUS_PROJEKT_ABGEBROCHEN);
        put("T_STATUS_PROJECT_COMPLETE", T_STATUS_PROJEKT_ABGESCHLOSSEN);
        put("T_STATUS_PROJECT_ERROR_PROCESSING", T_STATUS_PROJEKT_FEHLER_BEARBEITEN);
        put("T_STATUS_PROJECT_LICENSE_MISSING", T_STATUS_PROJEKT_LIZENZ_FEHLT);
        put("T_STATUS_PROJECT_QUALITY_CHECK", T_STATUS_PROJEKT_QUALITAT_SICHERN);
        // put("T_STATUS_PROJECT_USING_ALLOWED", T_STATUS_PROJEKT_VERWENDBAR);
        put("T_STATUS_PROJECT_REWORK", T_STATUS_PROJEKT_ZUR_UBERARBEITUNG);
        
        // campaign type tag 6
        put("T_CAMP_TYPE", T_CAMP_TYPE_LABEL);
        put("T_CAMP_TYPE_NATIONAL", T_CAMP_TYPE_NATIONAL_LABEL);
        put("T_CAMP_TYPE_REGIONAL", T_CAMP_TYPE_REGIONAL_LABEL);
        put("T_CAMP_TYPE_CATALINA", T_CAMP_TYPE_CATALINA_LABEL);
        put("T_CAMP_TYPE_DCARD", T_CAMP_TYPE_DCARD_LABEL);
        put("T_CAMP_TYPE_SUPPLIER", T_CAMP_TYPE_LIEFERANT_LABEL);
        
        // task status tag 8
        put("taskstatustag", TASK_STATUS_TAG_LABEL);
        put("taskplanned", PLANNED_LABEL);
        put("taskready", READY_LABEL);
        put("taskdeclined", DECLINED_LABEL);
        put("taskinprogress", IN_PROGRESS_LABEL);
        put("taskdone", DONE_LABEL);
        put("taskverified", VERIFIED_LABEL);
        put("tasksignedoff", SIGNED_OFF_LABEL);
        
        // resolution tag 4
        put("resolutiontag", RESOLUTION_TAG_LABEL);
        put("resolution_300P", RESOLUTION_300P_LABEL);
        put("resolution_150P", RESOLUTION_150P_LABEL);
        put("resolution_72P", RESOLUTION_72P_LABEL);
        
        put("imageextensiontag", IMAGE_EXTENSION_LABEL);
        put("image_extension_format_original", IMAGE_FORMAT_ORIGINAL_LABEL);
        put("image_extension_format_jpg", IMAGE_FORMAT_JPG_LABEL);
        put("image_extension_format_png", IMAGE_FORMAT_PNG_LABEL);
        
        // boolean tag 6
        put("isordertag", IS_ORDER_TAG_LABEL);
        put("isordertagvalue", IS_ORDER_TAG_LABEL);
        put("issalestag", IS_SALES_TAG_LABEL);
        put("issalestagvalue", IS_SALES_TAG_LABEL);
        put("isbaseunittag", IS_BASEUNIT_TAG_LABEL);
        put("isbaseunittagvalue", IS_BASEUNIT_TAG_LABEL);
        
        // suported languages
        /*put("supportedLanguages", SUPPORTED_LANGUAGES);
        put("en", EN);
        put("dr", DE);
        put("es", ES);
        put("fr", FR);
        
        put("language", LANGUAGE);
        put("en_US", EN_US);
        put("en_UK", EN_UK);
        put("de_DE", DE_DE);
        put("fr_FR", FR_FR);
        put("es_ES", ES_ES);*/
        
      }
    };
    
    Language_Labels = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        put(Constants.ENGLISH_US, ENGLISH_LABEL);
        put(Constants.FRENCH, FRENCH_LABEL);
        put(Constants.SPANISH, SPANISH_LABEL);
        put(Constants.GERMAN, GERMAN_LABEL);
      }
    };
    
    Tabs_Labels = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        put(SystemLevelIds.DEFAULT_DASHBOARD_TAB_ID, DEFAULT_DASHBOARD_TAB);
        put(SystemLevelIds.DEFAULT_DATA_INTEGRATION_TAB_ID, DEFAULT_DATA_INTEGRATION_TAB);
      }
    };
    
    // Smart Documents
    SMART_DOCUMENT_LABEL = "Smart Document__es_ES";
    
    // References
    STANDARD_ARTICLE_SMART_DOCUMENT_REFRENCE_ID = "Article-Smart Document Reference__es_ES";
    STANDARD_MARKETING_ARTICLE_SMART_DOCUMENT_REFRENCE_ID = "Marketing Article-Smart Document Reference__es_ES";
    
    REFERENCE_LABELS = new String[] { STANDARD_ARTICLE_SMART_DOCUMENT_REFRENCE_ID,
        STANDARD_MARKETING_ARTICLE_SMART_DOCUMENT_REFRENCE_ID };
    
    REFERENCE_SIDE_1_LABELS = new String[] { ARTICLES_LABEL, MARKETING_PRODUCT_LABEL };
    
    REFERENCE_SIDE_2_LABELS = new String[] { SMART_DOCUMENT_LABEL, SMART_DOCUMENT_LABEL };
  }
}
