package com.cs.core.runtime.interactor.constants.projectspecific;

import java.util.HashMap;

import org.springframework.stereotype.Component;

import com.cs.constants.SystemLevelIds;
import com.cs.core.runtime.interactor.constants.application.Constants;

@Component
public class InitializeDataLabels__en_US extends InitializeDataLabelKeys {
  
  public InitializeDataLabels__en_US()
  {
    ASSET_COVERFLOW_ATTRIBUTE_LABEL = "File Preview";
    ADDRESS_ATTRIBUTE_LABEL = "Address";
    DESCRIPTION_ATTRIBUTE_LABEL = "Description";
    DUE_DATE_ATTRIBUTE_LABEL = "Due Date";
    FIRST_NAME_ATTRIBUTE_LABEL = "First Name";
    LIST_PRICE_ATTRIBUTE_LABEL = "List Price";
    LONG_DESCRIPTION_ATTRIBUTE_LABEL = "Long Description";
    MINIMUM_PRICE_ATTRIBUTE_LABEL = "Minimum Price";
    PID_ATTRIBUTE_LABEL = "PID";
    PIN_CODE_ATTRIBUTE_LABEL = "Pin Code";
    SELLING_PRICE_ATTRIBUTE_LABEL = "Selling Price";
    SHORT_DESCRIPTION_ATTRIBUTE_LABEL = "Short Description";
    SKU_ATTRIBUTE_LABEL = "SKU";
    TELEPHONE_NUMBER_ATTRIBUTE_LABEL = "Telephone Number";
    DISCOUNT_ATTRIBUTE_LABEL = "Discount (%)";
    GTIN_ATTRIBUTE_LABEL = "GTIN";
    LAST_NAME_ATTRIBUTE_LABEL = "Last Name";
    MAXIMUM_PRICE_ATTRIBUTE_LABEL = "Maximum Price";
    
    CREATED_BY_ATTRIBUTE = "Created By";
    CREATED_ON_ATTRIBUTE = "Created On";
    LAST_MODIFIED_ATTRIBUTE = "Last Modified";
    LAST_MODIFIED_BY_ATTRIBUTE = "Last Modified By";
    NAME_ATTRIBUTE = "Name";
    
    DTP_ERROR_MARGIN_LABEL = "Error margin";
    DTP_MAX_NO_OF_SLOTS_ATTRIBUTE_LABEL = "Maximum Number of Slots";
    DTP_MINIMUM_SLOT_HEIGHT_ATTRIBUTE_LABEL = "Minimum Slot Height";
    DTP_MINIMUM_SLOT_WIDTH_ATTRIBUTE_LABEL = "Minimum Slot Width";
    DTP_DELTA_ATTRIBUTE_LABEL = "Delta";
    
    I_META_FILE_NAME = "I_META_FILE_NAME";
    I_META_DOCUMENT_TYPE = "I_META_DOCUMENT_TYPE";
    I_APPLICATION = "I_APPLICATION";
    I_CREATE_DATE = "I_CREATE_DATE";
    I_MODIFICATION_DATE = "I_MODIFICATION_DATE";
    I_META_FILE_SIZE = "I_META_FILE_SIZE";
    I_DIMENSIONS = "I_DIMENSIONS";
    I_DIMENSION_IN_INCH = "I_DIMENSION_IN_INCH";
    I_RESOLUTION = "I_RESOLUTION";
    I_BIT_DEPTH = "I_BIT_DEPTH";
    I_COLOR_MODE = "I_COLOR_MODE";
    I_COLOR_PROFILE = "I_COLOR_PROFILE";
    I_META_CREATOR_AUTHOR = "I_META_CREATOR_AUTHOR";
    I_META_CREATOR_STREET = "I_META_CREATOR_STREET";
    I_META_CREATOR_LOCATION = "I_META_CREATOR_LOCATION";
    I_META_CREATOR_STATE = "I_META_CREATOR_STATE";
    I_META_CREATOR_POSTAL_CODE = "I_META_CREATOR_POSTAL_CODE";
    I_META_CREATOR_COUNTRY = "I_META_CREATOR_COUNTRY";
    I_META_CREATOR_TEL = "I_META_CREATOR_TEL";
    I_META_CREATOR_EMAIL = "I_META_CREATOR_EMAIL";
    I_META_CREATOR_WWW = "I_META_CREATOR_WWW";
    I_META_HEADING = "I_META_HEADING";
    I_META_DESCRIPTION = "I_META_DESCRIPTION";
    I_META_KEYWORDS = "I_META_KEYWORDS";
    I_META_LOCATION_DETAIL = "I_META_LOCATION_DETAIL";
    I_META_LOCATION = "I_META_LOCATION";
    I_META_STATE = "I_META_STATE";
    I_META_COUNTRY = "I_META_COUNTRY";
    I_META_TITEL = "I_META_TITEL";
    I_META_COPYRIGHT = "I_META_COPYRIGHT";
    I_META_COPYRIGHT_STATUS = "I_META_COPYRIGHT_STATUS";
    I_META_EXPOSURE_INDEX = "I_META_EXPOSURE_INDEX";
    I_META_FOCAL_RANGE = "I_META_FOCAL_RANGE";
    I_META_MAX_BLINDING_VALUE = "I_META_MAX_BLINDING_VALUE";
    I_META_RECORDING_DATE = "I_META_RECORDING_DATE";
    I_META_EXPOSURE_CONTROLS = "I_META_EXPOSURE_CONTROLS";
    I_META_LIGHT_SOURCE = "I_META_LIGHT_SOURCE";
    I_META_SENSOR_TYPE = "I_META_SENSOR_TYPE";
    I_META_BRAND = "I_META_BRAND";
    I_META_MODELL = "I_META_MODELL";
    I_META_SERIAL_NUMBER = "I_META_SERIAL_NUMBER";
    I_META_PIXEL_X_DIMENSION = "I_META_PIXEL_X_DIMENSION";
    I_META_PIXEL_Y_DIMENSION = "I_META_PIXEL_Y_DIMENSION";
    I_META_HIGH_RESOLUTION = "I_META_HIGH_RESOLUTION";
    I_META_WIDTH_RESOLUTION = "I_META_WIDTH_RESOLUTION";
    I_META_X_RESOLUTION = "I_META_X_RESOLUTION";
    I_META_Y_RESOLUTION = "I_META_Y_RESOLUTION";
    
    // Tags
    IS_ORDER_TAG_LABEL = "isOrder";
    IS_SALES_TAG_LABEL = "isSales";
    IS_BASEUNIT_TAG_LABEL = "isBaseUnit";
    
    LISTING_STATUS_TAG_LABEL = "Listing Status";
    LISTING_STATUS_CATLOG_LABEL = "Catalog";
    LISTING_STATUS_IGNORED_LABEL = "Ignored";
    LISTING_STATUS_REJECTED_LABEL = "Rejected";
    LISTING_STATUS_ONBOARDING_POOL_LABEL = "Onboarding Pool";
    LISTING_STATUS_RECOMMENDED_LABEL = "Recommended";
    LISTING_STATUS_SHADOW_ASSORTMENT_LABEL = "Shadow Assortment";
    LISTING_STATUS_LISTED_LABEL = "Listed";
    LIFE_STATUS_TAG_LABEL = "Life Cycle Status";
    LIFE_STATUS_INBOX_LABEL = "Inbox";
    LIFE_STATUS_NO_INTEREST_LABEL = "No Interest";
    LIFE_STATUS_PREPARATION_LABEL = "Preparation";
    LIFE_STATUS_ACTIVE_LABEL = "Active";
    LIFE_STATUS_ACTIVE_BLOCKED_LABEL = "Active - Blocked";
    LIFE_STATUS_ACTIVE_BANNED_LABEL = "Active - Banned";
    LIFE_STATUS_RETIRED_LABEL = "Retired";
    LIFE_STATUS_ARCHIVED_LABEL = "Archived";
    LIFE_STATUS_DELETED_LABEL = "Deleted";
    STATUS_TAG_LABEL = "Status";
    ENRICHMENT_TAG_LABEL = "Enrichment";
    QUALITY_CHECK_TAG_LABEL = "Quality Check";
    TRANSLATION_TAG_LABEL = "Translation";
    APPROVAL_TAG_LABEL = "Approval";
    PRODUCTIVE_TAG_LABEL = "Productive";
    BLOCKED_FROM_PLANNING_LABEL = "Blocked from planning";
    AVAILABILITY_TAG_LABEL = "Availability";
    ON_REQUEST_LABEL = "On Request";
    ON_STOCK_LABEL = "On Stock";
    REGULARLY_AVAILABLE_LABEL = "Regularly Available";
    DROP_SHIPPING_LABEL = "Drop Shipping";
    LANGUAGE_TAG_LABEL = "Language";
    ENGLISH_LABEL = "English";
    GERMAN_LABEL = "German";
    SPANISH_LABEL = "Spanish";
    ITALIAN_LABEL = "Italian";
    FRENCH_LABEL = "French";
    PORTUGESE_LABEL = "Portugese";
    SWEDISH_LABEL = "Swedish";
    
    DEFAULT_DATA_INTEGRATION_TAB = "DefaultDataIntegrationTab";
    DEFAULT_DASHBOARD_TAB = "DefaultDashboardTab";
    
    SUPPORTED_LANGUAGES = "SupportedLanguages";
    EN = "en";
    DE = "de";
    FR = "fr";
    ES = "es";
    
    LANGUAGE = "language";
    EN_US = "English (U.S)";
    EN_UK = "English (U.K)";
    DE_DE = "Deutsch";
    FR_FR = "Fran�ais";
    ES_ES = "Espa�ol";
    
    T_STATUS_SYSTEM_LABEL = "Status";
    T_STATUS_SYSTEM_NEU_LABEL = "Neu";
    T_STATUS_SYSTEM_INAKTIV_LABEL = "Inaktiv";
    T_STATUS_SYSTEM_AKTIV_LABEL = "Aktiv";
    T_STATUS_SYSTEM_ARCHIVIERT_LABEL = "Archiviert";
    T_STATUS_SYSTEM_GELOESCHT_LABEL = "Gelöscht";
    T_STATUS_SYSTEM_PREPARE_LABEL = "Vorbereitung";
    T_STATUS_SYSTEM_BLOCKED_LABEL = "Gesperrt";
    T_STATUS_PROJECT_LABEL = "Projektstatus";
    
    T_CAMPAIGN_GOALS_LABEL = "Goals";
    T_GOALS_BRAND_PROMOTION_LABEL = "Brand Promotion";
    T_GOALS_SEASONAL_PROMOTION_LABEL = "Seasonal Promotion";
    T_GOALS_NEW_ARRIVALS_LABEL = "New Arrivals";
    T_GOALS_PROMOTION_HIGH_MARGIN_LABEL = "Promotion of Higher Margin Products";
    T_GOALS_INVENTORY_CLEARANCE_LABEL = "Inventory Clearance";
    T_GOALS_LOYALTY_POINTS_LABEL = "Niche group promotion (Loyalty Points)";
    T_GOALS_SPECIAL_TOPIC_LABEL = "Special topic promotion";
    T_GOALS_ACQUIRE_NEW_CUSTOMERS_LABEL = "Acquire new customers";
    T_GOALS_RETAIN_EXISTING_CUSTOMERS_LABEL = "Retain existing customers";
    
    T_CAMP_TYPE_LABEL = "Kampagnen-Typ";
    T_CAMP_TYPE_NATIONAL_LABEL = "National";
    T_CAMP_TYPE_REGIONAL_LABEL = "Regional";
    T_CAMP_TYPE_CATALINA_LABEL = "Catalina";
    T_CAMP_TYPE_DCARD_LABEL = "DeutschlandCard";
    T_CAMP_TYPE_LIEFERANT_LABEL = "Lieferant";
    TASK_STATUS_TAG_LABEL = "Task-Status";
    PLANNED_LABEL = "Planned";
    READY_LABEL = "Ready";
    DECLINED_LABEL = "Declined";
    IN_PROGRESS_LABEL = "In_Progress";
    DONE_LABEL = "Done";
    VERIFIED_LABEL = "Verified";
    SIGNED_OFF_LABEL = "Signed_Off";
    
    RESOLUTION_TAG_LABEL = "Resolution";
    RESOLUTION_300P_LABEL = "300_dpi";
    RESOLUTION_150P_LABEL = "150_dpi";
    RESOLUTION_72P_LABEL = "72_dpi";
    IMAGE_EXTENSION_LABEL = "Image Extension";
    IMAGE_FORMAT_JPG_LABEL = "jpg";
    IMAGE_FORMAT_PNG_LABEL = "png";
    IMAGE_FORMAT_ORIGINAL_LABEL = "original";
    
    T_STATUS_PROJEKT_VERWENDBAR = "Verwendbar";
    T_STATUS_PROJEKT_IN_PLANUNG = "In Planung";
    T_STATUS_PROJEKT_ABGESCHLOSSEN = "abgeschlossen";
    T_STATUS_PROJEKT_ZUR_UBERARBEITUNG = "zur Überarbeitung";
    T_STATUS_PROJEKT_QUALITAT_SICHERN = "Qualität sichern";
    T_STATUS_PROJEKT_FEHLER_BEARBEITEN = "Fehler bearbeiten";
    T_STATUS_PROJEKT_LIZENZ_FEHLT = "Lizenz fehlt";
    T_STATUS_PROJEKT_ABGEBROCHEN = "abgebrochen";
    
    CREATED_EVENT_LABEL = "Created";
    
    LANGUAGE_TAXONOMY_LABEL = "Language";
    
    PRICING_PROPERTY_COLLECTION_LABEL = "Pricing";
    ARTICLE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "General Information";
    MARKET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Market General Information";
    ASSET_GENERAL_INFORMATION_PROPERTY_COLLETION_LABEL = "Asset Information";
    CAMPAIGN_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "General Information";
    PROMOTION_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Promotion General Information";
    SUPPLIER_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Supplier General Information";
    TEXTASSET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Text-Asset General Information";
    DEFAULT_X_RAY_PROPERTY_COLLECTION_LABEL = "Default X-Ray Collection";
    METADATA_COLLECTION_LABEL = "Metadata";
    UNIT_DEFAULT_PROPERTYCOLLECTION_LABEL = "Unit Information";
    DTP_TEMPLATE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL = "Template General Information";
    DTP_DOCUMENT_TEMPLATE_INFORMATION_PROPERTY_COLLECTION_LABEL = "Document Template Information";
    DTP_TEMPLATE_FILE_INFOMATION_PROPERTY_COLLECTION_LABEL = "Template File Information";
    
    STANDARD_ARTICLE_KLASS_LABEL = "Article";
    STANDARD_SET_KLASS_LABEL = "Set";
    STANDARD_COLLETION_KLASS_LABEL = "Collection";
    STANDARD_CHANNEL_CLASSES_LABEL = "Channel Classes";
    STANDARD_PRODUCT_TYPES_LABEL = "Product Types";
    STANDARD_SINGLE_ARTICLE = "Single Article";
    STANDARD_ATTRIBUTION_CLASSES_LABEL = "Attribution Classes";
    STANDARD_FILE_KLASS_LABEL = "File";
    STANDARD_VERSION_KLASS_LABEL = "Version Class";
    STANDARD_GOLDEN_ARTICLE_KLASS_LABEL = "Golden Article";
    
    MARKETING_PRODUCT_LABEL = "Marketing Product";
    MARKETING_BUNDLE_LABEL = "Marketing Bundle";
    
    PROMOTION_LABEL = "Promotion";
    SUPPLIER_LABEL = "Supplier";
    MARKET_LABEL = "Market";
    STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL = "PublicationTemplate";
    STANDARD_DTP_PUBLICATION_LABEL = "Publication";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL = "DocumentTemplate";
    STANDARD_DTP_PRODUCT_TEMPLATE_LABEL = "ProductTemplate";
    STANDARD_DTP_ABSTRACT_DOCUMENT_TEMPLATE_LABEL = "Abstract Document Template";
    STANDARD_DTP_ABSTRACT_PRODUCT_TEMPLATE_LABEL = "Abstract Product Template";
    STANDARD_DTP_ABSTRACT_PUBLICATION_TEMPLATE_LABEL = "Abstract Publication Template";
    STANDARD_DTP_ABSTRACT_PUBLICATION_LABEL = "Abstract Publication";
    
    STANDARD_DTP_ABSTRACT_DOCUMENT_LABEL = "Abstract Document";
    STANDARD_DTP_DOCUMENT_LABEL = "Document";
    STANDARD_DTP_DOCUMENT_VARIANT_LABEL = "Document Variant";
    ADMIN_LABEL = "admin";
    
    SUPPLIERS_LABEL = "Supplier";
    MARKETPLACES_LABEL = "Marketplaces";
    DISTRIBUTORS_LABEL = "Distributors";
    WHOLESALERS_LABEL = "Wholesalers";
    TRANSLATION_AGENCY_LABEL = "Translation Agency";
    CONTENT_ENRICHMENT_AGENCY_LABEL = "Content Enrichment Agency";
    DIGITAL_ASSET_AGENCY_LABEL = "Digital Asset Agency";
    
    APPROVER_ROLE_LABEL = "Approver(Sign-Off)";
    OWNER_ROLE_LABEL = "Owner(Responsible)";
    SUBSCRIBER_ROLE_LABEL = "Subscriber(Informed)";
    CONTRIBUTOR_ROLE_LABEL = "Contributor(Consulted)";
    REVIEWER_ROLE_LABEL = "Reviewer(Verify)";
    SENIOR_MANAGER_ROLE_LABEL = "Senior Manager(Accountable)";
    ASSIGNEE_ROLE_LABEL = "Assignee";
    
    // Role
    RESPONSIBLE_ROLE_LABEL = "Responsible";
    ACCOUNTABLE_ROLE_LABEL = "Accountable";
    CONSULTED_ROLE_LABEL = "Consulted";
    INFORMED_ROLE_LABEL = "Informed";
    VERIFY_ROLE_LABEL = "Verify";
    SIGNOFF_ROLE_LABEL = "Sign-off";
    ADMIN_ROLE_LABEL = "Admin";
    
    RACIVS_ROLE_LABELS = new String[] { RESPONSIBLE_ROLE_LABEL, ACCOUNTABLE_ROLE_LABEL,
        CONSULTED_ROLE_LABEL, INFORMED_ROLE_LABEL, VERIFY_ROLE_LABEL, SIGNOFF_ROLE_LABEL,
        ADMIN_ROLE_LABEL };
    
    STANDARD_ARTICLE_ASSET_RELATIONSHIP_LABEL = "Article-Asset Relationship";
    STANDARD_MARKET_ASSET_RELATIONSHIP_LABEL = "Market-Asset Relationship";
    STANDARD_CAMPAIGN_ASSET_RELATIONSHIP_LABEL = "Campaign-Asset Relationship";
    STANDARD_CAMPAIGN_CAMPAIGN_RELATIONSHIP_LABEL = "Campaign-Campaign Relationship";
    STANDARD_TEXTASSET_ASSET_RELATIONSHIP_LABEL = "TextAsset-Asset Relationship";
    STANDARD_SUPPLIER_ASSET_RELATIONSHIP_LABEL = "Supplier-Asset Relationship";
    STANDARD_PROMOTION_ASSET_RELATIONSHIP_LABEL = "Promotion-Asset Relationship";
    STANDARD_ARTICLE_MARKET_RELATIONSHIP_LABEL = "Article - Market Relationship";
    STANDARD_ARTICLE_GOLDEN_ARTICLE_RELATIONSHIP_LABEL = "Article-GoldenArticle Relationship";
    STANDARD_ARTICLE_MARKETING_ARTICLE_RELATIONSHIP_LABEL = "Article-MarketingArticle Relationship";
    
    STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_LABEL = "PublicationTemplate - DocumentTemplate Relationship";
    STANDARD_DTP_PRODUCT_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "Product Template - Asset Relationship";
    STANDARD_DTP_PUBLICATION_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "Publication Template - Asset Relationship";
    STANDARD_DTP_DOCUMENT_TEMPLATE_ASSET_RELATIONSHIP_LABEL = "DocumentTemplate - Asset Relationship";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_ARTICLES_RELATIONSHIP_LABEL = "DocumentTemplate - Marketing Articles Relationship";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_PRODUCT_TEMPLATES_RELATIONSHIP_LABEL = "DocumentTemplate - Product Template Relationship";
    STANDARD_DTP_DOCUMENT_TEMPLATE_PAGE_PREVIEW_RELATIONSHIP_LABEL = "DocumentTemplate - Page Preview Relationship";
    STANDARD_DTP_PUBLICATION_DTP_PUBLICATION_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Publication Template";
    STANDARD_DTP_PUBLICATION_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Document Template";
    STANDARD_DTP_PUBLICATION_DTP_PRODUCT_TEMPLATE_RELATIONSHIP_LABEL = "Publication - Product Template";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_BUNDLE_RELATIONSHIP_LABEL = "DocumentTemplate - Marketing Bundle Relationship";
    STANDARD_MARKETING_ARTICLE_ASSET_RELATIONSHIP_LABEL = "MarketingArticle - Asset Relationship";
    STANDARD_MARKETING_BUNDLE_ASSET_RELATIONSHIP_LABEL = "MarketingBundle - Asset Relationship";
    PAGE_PREVIEWS = "Page Previews";
    
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_ARTICLES_RELATIONSHIP_LABEL = "Document Template - Marketing Article";
    STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_BUNDLES_RELATIONSHIP_LABEL = "Document Template - Marketing Bundle";
    STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL = "Publication Template - Document Template";
    
    IMAGES = "Images";
    STANDARD_SYSTEM = "Standard System";
    STANDARD_CAMPAIGN_KLASS_LABEL = "Campaign";
    
    STANDARD_ORGANIZATION = "Standard Organization";
    
    // _LABEL = "side 1" ;
    ARTICLES_LABEL = "Articles";
    TARGETS_LABEL = "Targets";
    CAMPAIGN_LABEL = "Campaign";
    TEXTASSET_LABEL = "TextAsset";
    SUPPLIER_LABEL = "Supplier";
    PROMOTION_LABEL = "Promotion";
    
    STANDARD_PROPERTY_COLLECTION_TAB_LABEL = "Properties";
    STANDARD_RELATIONSHIP_TAB_LABEL = "Relationships";
    STANDARD_CONTEXT_TAB_LABEL = "Contexts";
    STANDARD_TASK_TAB_LABEL = "Tasks";
    STANDARD_TIMELINE_TAB_LABEL = "Timeline";
    STANDARD_RENDITION_TAB_LABEL = "Renditions";
    STANDARD_OVERVIEW_TAB_LABEL = "Overview";
    STANDARD_MDM_TAB_LABEL = "Mdm";
    
    STANDARD_VIDEO_KLASS_LABEL = "Video";
    STANDARD_DOCUMENT_KLASS_LABEL = "Document";
    STANDARD_IMAGE_KLASS_LABEL = "Image";
    STANDARD_ATTACHMENT_KLASS_LABEL = "Attachment";
    STANDARD_ASSET_KLASS_LABEL = "Asset";
    STANDARD_SMARTDOCUMENT_KLASS_LABEL = "Smart Document";
    
    STANDARD_OVERVIEW_TAB_LABEL = "overview_tab";
    STANDARD_MDM_TAB_LABEL = "mdm_tab";
    STANDARD_DUPLICATE_TAB_LABEL = "duplicates_tab";
    STANDARD_PROPERTY_COLLECTION_TAB_LABEL = "property_collection_tab";
    STANDARD_RELATIONSHIP_TAB_LABEL = "relationship_tab";
    STANDARD_CONTEXT_TAB_LABEL = "context_tab";
    STANDARD_TASK_TAB_LABEL = "task_tab";
    STANDARD_TIMELINE_TAB_LABEL = "timeline_tab";
    STANDARD_RENDITION_TAB_LABEL = "renditions_tab";
    STANDARD_CONFIGURATION_TAB_LABEL = "configurations_tab";
    
    STANDARD_TAB_LABELS = new String[] { STANDARD_OVERVIEW_TAB_LABEL,
        STANDARD_PROPERTY_COLLECTION_TAB_LABEL, STANDARD_RELATIONSHIP_TAB_LABEL,
        STANDARD_CONTEXT_TAB_LABEL, STANDARD_TASK_TAB_LABEL, 
        STANDARD_TIMELINE_TAB_LABEL, STANDARD_RENDITION_TAB_LABEL,
        STANDARD_CONFIGURATION_TAB_LABEL, STANDARD_MDM_TAB_LABEL, STANDARD_DUPLICATE_TAB_LABEL };
    
    DTP_KLASS_LABELS = new String[] { STANDARD_DTP_ABSTRACT_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_ABSTRACT_PRODUCT_TEMPLATE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, STANDARD_DTP_ABSTRACT_PUBLICATION_TEMPLATE_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL };
    
    DTP_PUBLICATION_LABELS = new String[] { STANDARD_DTP_ABSTRACT_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_LABEL };
    
    DTP_DOCUMENT_LABELS = new String[] { STANDARD_DTP_ABSTRACT_DOCUMENT_LABEL,
        STANDARD_DTP_DOCUMENT_LABEL, STANDARD_DTP_DOCUMENT_VARIANT_LABEL };
    
    ATTRIBUTE_LABELS = new String[] { ASSET_COVERFLOW_ATTRIBUTE_LABEL, ADDRESS_ATTRIBUTE_LABEL,
        DESCRIPTION_ATTRIBUTE_LABEL, DUE_DATE_ATTRIBUTE_LABEL, FIRST_NAME_ATTRIBUTE_LABEL,
        LIST_PRICE_ATTRIBUTE_LABEL, LONG_DESCRIPTION_ATTRIBUTE_LABEL, MINIMUM_PRICE_ATTRIBUTE_LABEL,
        PID_ATTRIBUTE_LABEL, PIN_CODE_ATTRIBUTE_LABEL, SELLING_PRICE_ATTRIBUTE_LABEL,
        SHORT_DESCRIPTION_ATTRIBUTE_LABEL, SKU_ATTRIBUTE_LABEL, TELEPHONE_NUMBER_ATTRIBUTE_LABEL,
        DISCOUNT_ATTRIBUTE_LABEL, GTIN_ATTRIBUTE_LABEL, LAST_NAME_ATTRIBUTE_LABEL,
        MAXIMUM_PRICE_ATTRIBUTE_LABEL, CREATED_BY_ATTRIBUTE, CREATED_ON_ATTRIBUTE,
        LAST_MODIFIED_ATTRIBUTE, LAST_MODIFIED_BY_ATTRIBUTE, NAME_ATTRIBUTE,
        DTP_MAX_NO_OF_SLOTS_ATTRIBUTE_LABEL, DTP_MINIMUM_SLOT_WIDTH_ATTRIBUTE_LABEL,
        DTP_MINIMUM_SLOT_HEIGHT_ATTRIBUTE_LABEL, DTP_ERROR_MARGIN_LABEL,
        DTP_DELTA_ATTRIBUTE_LABEL };
    
    METADATA_ATTRIBUTES_LABELS = new String[] { I_META_FILE_NAME, I_META_DOCUMENT_TYPE,
        I_APPLICATION, I_CREATE_DATE, I_MODIFICATION_DATE, I_META_FILE_SIZE, I_DIMENSIONS,
        I_DIMENSION_IN_INCH, I_RESOLUTION, I_BIT_DEPTH, I_COLOR_MODE, I_COLOR_PROFILE,
        I_META_CREATOR_AUTHOR, I_META_CREATOR_STREET, I_META_CREATOR_LOCATION, I_META_CREATOR_STATE,
        I_META_CREATOR_POSTAL_CODE, I_META_CREATOR_COUNTRY, I_META_CREATOR_TEL,
        I_META_CREATOR_EMAIL, I_META_CREATOR_WWW, I_META_HEADING, I_META_DESCRIPTION,
        I_META_KEYWORDS, I_META_LOCATION_DETAIL, I_META_LOCATION, I_META_STATE, I_META_COUNTRY,
        I_META_TITEL, I_META_COPYRIGHT, I_META_COPYRIGHT_STATUS, I_META_EXPOSURE_INDEX,
        I_META_FOCAL_RANGE, I_META_MAX_BLINDING_VALUE, I_META_RECORDING_DATE,
        I_META_EXPOSURE_CONTROLS, I_META_LIGHT_SOURCE, I_META_SENSOR_TYPE, I_META_BRAND,
        I_META_MODELL, I_META_SERIAL_NUMBER, I_META_PIXEL_X_DIMENSION, I_META_PIXEL_Y_DIMENSION,
        I_META_HIGH_RESOLUTION, I_META_WIDTH_RESOLUTION, I_META_X_RESOLUTION, I_META_Y_RESOLUTION };
    
    TAG_LABELS = new String[] { LISTING_STATUS_TAG_LABEL, LISTING_STATUS_CATLOG_LABEL,
        LISTING_STATUS_IGNORED_LABEL, LISTING_STATUS_REJECTED_LABEL,
        LISTING_STATUS_ONBOARDING_POOL_LABEL, LISTING_STATUS_RECOMMENDED_LABEL,
        LISTING_STATUS_SHADOW_ASSORTMENT_LABEL, LISTING_STATUS_LISTED_LABEL, LIFE_STATUS_TAG_LABEL,
        LIFE_STATUS_INBOX_LABEL, LIFE_STATUS_NO_INTEREST_LABEL, LIFE_STATUS_PREPARATION_LABEL,
        LIFE_STATUS_ACTIVE_LABEL, LIFE_STATUS_ACTIVE_BLOCKED_LABEL, LIFE_STATUS_ACTIVE_BANNED_LABEL,
        LIFE_STATUS_RETIRED_LABEL, LIFE_STATUS_ARCHIVED_LABEL, LIFE_STATUS_DELETED_LABEL,
        STATUS_TAG_LABEL, ENRICHMENT_TAG_LABEL, QUALITY_CHECK_TAG_LABEL, TRANSLATION_TAG_LABEL,
        APPROVAL_TAG_LABEL, PRODUCTIVE_TAG_LABEL, BLOCKED_FROM_PLANNING_LABEL,
        AVAILABILITY_TAG_LABEL, ON_REQUEST_LABEL, ON_STOCK_LABEL, REGULARLY_AVAILABLE_LABEL,
        DROP_SHIPPING_LABEL, LANGUAGE_TAG_LABEL, ENGLISH_LABEL, GERMAN_LABEL, SPANISH_LABEL,
        ITALIAN_LABEL, FRENCH_LABEL, PORTUGESE_LABEL, SWEDISH_LABEL };
    
    PROPERTY_COLLECTION_LABELS = new String[] { PRICING_PROPERTY_COLLECTION_LABEL,
        ARTICLE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        MARKET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        ASSET_GENERAL_INFORMATION_PROPERTY_COLLETION_LABEL,
        CAMPAIGN_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        PROMOTION_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        SUPPLIER_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        TEXTASSET_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DEFAULT_X_RAY_PROPERTY_COLLECTION_LABEL, METADATA_COLLECTION_LABEL,
        UNIT_DEFAULT_PROPERTYCOLLECTION_LABEL,
        DTP_TEMPLATE_GENERAL_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DTP_DOCUMENT_TEMPLATE_INFORMATION_PROPERTY_COLLECTION_LABEL,
        DTP_TEMPLATE_FILE_INFOMATION_PROPERTY_COLLECTION_LABEL };
    
    TARGET_KLASS_LABELS = new String[] { MARKET_LABEL };
    
    PIM_KLASS_LABELS = new String[] { STANDARD_ARTICLE_KLASS_LABEL, STANDARD_PRODUCT_TYPES_LABEL,
        STANDARD_CHANNEL_CLASSES_LABEL, STANDARD_ATTRIBUTION_CLASSES_LABEL, STANDARD_SINGLE_ARTICLE,
        STANDARD_FILE_KLASS_LABEL, STANDARD_VERSION_KLASS_LABEL,
        STANDARD_GOLDEN_ARTICLE_KLASS_LABEL };
    
    MAM_KLASS_LABELS = new String[] { STANDARD_ATTACHMENT_KLASS_LABEL, STANDARD_ASSET_KLASS_LABEL,
        STANDARD_IMAGE_KLASS_LABEL, STANDARD_VIDEO_KLASS_LABEL, STANDARD_DOCUMENT_KLASS_LABEL,
        STANDARD_SMARTDOCUMENT_KLASS_LABEL };
    
    ROLES = new String[] { APPROVER_ROLE_LABEL, OWNER_ROLE_LABEL, SUBSCRIBER_ROLE_LABEL,
        CONTRIBUTOR_ROLE_LABEL, REVIEWER_ROLE_LABEL, SENIOR_MANAGER_ROLE_LABEL,
        ASSIGNEE_ROLE_LABEL };
    
    RELATIONSHIP_LABELS = new String[] { STANDARD_ARTICLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_MARKET_ASSET_RELATIONSHIP_LABEL, STANDARD_CAMPAIGN_ASSET_RELATIONSHIP_LABEL,
        STANDARD_CAMPAIGN_CAMPAIGN_RELATIONSHIP_LABEL, STANDARD_TEXTASSET_ASSET_RELATIONSHIP_LABEL,
        STANDARD_SUPPLIER_ASSET_RELATIONSHIP_LABEL, STANDARD_PROMOTION_ASSET_RELATIONSHIP_LABEL,
        STANDARD_ARTICLE_MARKET_RELATIONSHIP_LABEL,
        STANDARD_ARTICLE_GOLDEN_ARTICLE_RELATIONSHIP_LABEL,
        STANDARD_MARKETING_ARTICLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_MARKETING_BUNDLE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_ARTICLES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_MARKETING_BUNDLES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LINKED_PRODUCT_TEMPLATES_RELATIONSHIP_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_PAGE_PREVIEW_RELATIONSHIP_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_PRODUCT_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_DTP_PUBLICATION_TEMPLATE_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_ASSET_RELATIONSHIP_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_DTP_DOCUMENT_TEMPLATE_RELATIONSHIP_LABEL };
    
    RELATIONSHIP_SIDE_1_LABELS = new String[] { ARTICLES_LABEL, MARKET_LABEL,
        CAMPAIGN_LABEL, CAMPAIGN_LABEL, TEXTASSET_LABEL, SUPPLIER_LABEL,
        PROMOTION_LABEL, ARTICLES_LABEL, ARTICLES_LABEL,
        MARKETING_PRODUCT_LABEL, MARKETING_BUNDLE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, STANDARD_DTP_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_LABEL, STANDARD_DTP_PUBLICATION_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL, STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL };
    
    RELATIONSHIP_SIDE_2_LABELS = new String[] { IMAGES, IMAGES, IMAGES, IMAGES, IMAGES,
        CAMPAIGN_LABEL, IMAGES, IMAGES, IMAGES, MARKET_LABEL, IMAGES,
        STANDARD_GOLDEN_ARTICLE_KLASS_LABEL, IMAGES, IMAGES, MARKET_LABEL,
        IMAGES, IMAGES, IMAGES, MARKETING_PRODUCT_LABEL, MARKETING_BUNDLE_LABEL,
        STANDARD_DTP_PRODUCT_TEMPLATE_LABEL, PAGE_PREVIEWS, IMAGES,
        STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL, STANDARD_DTP_PRODUCT_TEMPLATE_LABEL,
        STANDARD_DTP_PUBLICATION_TEMPLATE_LABEL, IMAGES, STANDARD_DTP_DOCUMENT_TEMPLATE_LABEL };
    
    TAGS_LABELS = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        
        // status
        put("statustag", STATUS_TAG_LABEL);
        put("enrichmenttag", ENRICHMENT_TAG_LABEL);
        put("qualitychecktag", QUALITY_CHECK_TAG_LABEL);
        put("translationtag", TRANSLATION_TAG_LABEL);
        put("approvaltag", APPROVAL_TAG_LABEL);
        put("productivetag", PRODUCTIVE_TAG_LABEL);
        put("blockedfromplanning", BLOCKED_FROM_PLANNING_LABEL);
        
        // availability
        put("availabilitytag", AVAILABILITY_TAG_LABEL);
        put("onrequest", ON_REQUEST_LABEL);
        put("onstock", ON_STOCK_LABEL);
        put("regularlyavailable", REGULARLY_AVAILABLE_LABEL);
        put("dropshipping", DROP_SHIPPING_LABEL);
        
        // lagnguage tag 8
        /* put("languagetag",LANGUAGE_TAG_LABEL);
        put("english",ENGLISH_LABEL);
        put("german",GERMAN_LABEL);
        put("spanish",SPANISH_LABEL);
        put("italian",ITALIAN_LABEL);
        put("french",FRENCH_LABEL);
        put("portugese",PORTUGESE_LABEL);
        put("swedish",SWEDISH_LABEL);*/
        
        // life cylcel status tag 10
        put("lifestatustag", LIFE_STATUS_TAG_LABEL);
        put("life_status_inbox", LIFE_STATUS_INBOX_LABEL);
        put("life_status_nointerest", LIFE_STATUS_NO_INTEREST_LABEL);
        put("life_status_preparation", LIFE_STATUS_PREPARATION_LABEL);
        put("life_status_active", LIFE_STATUS_ACTIVE_LABEL);
        put("life_status_activeblocked", LIFE_STATUS_ACTIVE_BLOCKED_LABEL);
        put("life_status_activebanned", LIFE_STATUS_ACTIVE_BANNED_LABEL);
        put("life_status_retired", LIFE_STATUS_RETIRED_LABEL);
        put("life_status_archived", LIFE_STATUS_ARCHIVED_LABEL);
        put("life_status_deleted", LIFE_STATUS_DELETED_LABEL);
        
        // listing status tag 8
        put("listingstatustag", LISTING_STATUS_TAG_LABEL);
        put("listing_status_catlog", LISTING_STATUS_CATLOG_LABEL);
        put("listing_status_ignored", LISTING_STATUS_IGNORED_LABEL);
        put("listing_status_rejected", LISTING_STATUS_REJECTED_LABEL);
        put("listing_status_onboardingpool", LISTING_STATUS_ONBOARDING_POOL_LABEL);
        put("listing_status_recommended", LISTING_STATUS_RECOMMENDED_LABEL);
        put("listing_status_shadowassortment", LISTING_STATUS_SHADOW_ASSORTMENT_LABEL);
        put("listing_status_listed", LISTING_STATUS_LISTED_LABEL);
        
        // system status tag 8
        put("T_STATUS_SYSTEM", T_STATUS_SYSTEM_LABEL);
        put("T_STATUS_SYSTEM_NEW", T_STATUS_SYSTEM_NEU_LABEL);
        put("T_STATUS_SYSTEM_INACTIV", T_STATUS_SYSTEM_INAKTIV_LABEL);
        put("T_STATUS_SYSTEM_ACTIV", T_STATUS_SYSTEM_AKTIV_LABEL);
        put("T_STATUS_SYSTEM_ARCHIVED", T_STATUS_SYSTEM_ARCHIVIERT_LABEL);
        put("T_STATUS_SYSTEM_DELETED", T_STATUS_SYSTEM_GELOESCHT_LABEL);
        put("T_STATUS_SYSTEM_PREPARE", T_STATUS_SYSTEM_PREPARE_LABEL);
        put("T_STATUS_SYSTEM_BLOCKED", T_STATUS_SYSTEM_BLOCKED_LABEL);
        
        // project status 9
        
        put("T_STATUS_PROJECT", T_STATUS_PROJECT_LABEL);
        put("T_STATUS_PROJECT_IN_PLANNING", T_STATUS_PROJEKT_IN_PLANUNG);
        put("T_STATUS_PROJECT_CANCELED", T_STATUS_PROJEKT_ABGEBROCHEN);
        put("T_STATUS_PROJECT_COMPLETE", T_STATUS_PROJEKT_ABGESCHLOSSEN);
        put("T_STATUS_PROJECT_ERROR_PROCESSING", T_STATUS_PROJEKT_FEHLER_BEARBEITEN);
        put("T_STATUS_PROJECT_LICENSE_MISSING", T_STATUS_PROJEKT_LIZENZ_FEHLT);
        put("T_STATUS_PROJECT_QUALITY_CHECK", T_STATUS_PROJEKT_QUALITAT_SICHERN);
        // put("T_STATUS_PROJECT_USING_ALLOWED", T_STATUS_PROJEKT_VERWENDBAR);
        put("T_STATUS_PROJECT_REWORK", T_STATUS_PROJEKT_ZUR_UBERARBEITUNG);
        
        // campaign type tag 6
        put("T_CAMP_TYPE", T_CAMP_TYPE_LABEL);
        put("T_CAMP_TYPE_NATIONAL", T_CAMP_TYPE_NATIONAL_LABEL);
        put("T_CAMP_TYPE_REGIONAL", T_CAMP_TYPE_REGIONAL_LABEL);
        put("T_CAMP_TYPE_CATALINA", T_CAMP_TYPE_CATALINA_LABEL);
        put("T_CAMP_TYPE_DCARD", T_CAMP_TYPE_DCARD_LABEL);
        put("T_CAMP_TYPE_SUPPLIER", T_CAMP_TYPE_LIEFERANT_LABEL);
        
        // task status tag 8
        put("taskstatustag", TASK_STATUS_TAG_LABEL);
        put("taskplanned", PLANNED_LABEL);
        put("taskready", READY_LABEL);
        put("taskdeclined", DECLINED_LABEL);
        put("taskinprogress", IN_PROGRESS_LABEL);
        put("taskdone", DONE_LABEL);
        put("taskverified", VERIFIED_LABEL);
        put("tasksignedoff", SIGNED_OFF_LABEL);
        
        // resolution tag 4
        put("resolutiontag", RESOLUTION_TAG_LABEL);
        put("resolution_300P", RESOLUTION_300P_LABEL);
        put("resolution_150P", RESOLUTION_150P_LABEL);
        put("resolution_72P", RESOLUTION_72P_LABEL);
        
        put("imageextensiontag", IMAGE_EXTENSION_LABEL);
        put("image_extension_format_original", IMAGE_FORMAT_ORIGINAL_LABEL);
        put("image_extension_format_jpg", IMAGE_FORMAT_JPG_LABEL);
        put("image_extension_format_png", IMAGE_FORMAT_PNG_LABEL);
        
        // boolean tag 6
        put("isordertag", IS_ORDER_TAG_LABEL);
        put("isordertagvalue", IS_ORDER_TAG_LABEL);
        put("issalestag", IS_SALES_TAG_LABEL);
        put("issalestagvalue", IS_SALES_TAG_LABEL);
        put("isbaseunittag", IS_BASEUNIT_TAG_LABEL);
        put("isbaseunittagvalue", IS_BASEUNIT_TAG_LABEL);
        
        // suported languages
        /*  put("supportedLanguages", SUPPORTED_LANGUAGES);
        put("en", EN);
        put("dr", DE);
        put("es", ES);
        put("fr", FR);
        
        put("language", LANGUAGE);
        put("en_US", EN_US);
        put("en_UK", EN_UK);
        put("de_DE", DE_DE);
        put("fr_FR", FR_FR);
        put("es_ES", ES_ES);*/
        
      }
    };
    
    Language_Labels = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        put(Constants.ENGLISH_US, ENGLISH_LABEL);
        put(Constants.FRENCH, FRENCH_LABEL);
        put(Constants.SPANISH, SPANISH_LABEL);
        put(Constants.GERMAN, GERMAN_LABEL);
      }
    };
    
    Tabs_Labels = new HashMap<String, String>()
    {
      
      private static final long serialVersionUID = 1L;
      
      {
        put(SystemLevelIds.DEFAULT_DASHBOARD_TAB_ID, DEFAULT_DASHBOARD_TAB);
        put(SystemLevelIds.DEFAULT_DATA_INTEGRATION_TAB_ID, DEFAULT_DATA_INTEGRATION_TAB);
      }
    };
    
    // Smart Documents
    SMART_DOCUMENT_LABEL = "Smart Document";
    
    // References
    STANDARD_ARTICLE_SMART_DOCUMENT_REFRENCE_ID = "Article-Smart Document Reference";
    STANDARD_MARKETING_ARTICLE_SMART_DOCUMENT_REFRENCE_ID = "Marketing Article-Smart Document Reference";
    
    REFERENCE_LABELS = new String[] { STANDARD_ARTICLE_SMART_DOCUMENT_REFRENCE_ID,
        STANDARD_MARKETING_ARTICLE_SMART_DOCUMENT_REFRENCE_ID };
    
    REFERENCE_SIDE_1_LABELS = new String[] { ARTICLES_LABEL, MARKETING_PRODUCT_LABEL };
    
    REFERENCE_SIDE_2_LABELS = new String[] { SMART_DOCUMENT_LABEL, SMART_DOCUMENT_LABEL };
  }
}
