package com.cs.di.workflow.constants;


public enum ExportSubType
{
  EXPORT_ALL, EXPORT_SELECTED, TAXONOMY_BASED_EXPORT, WITHOUT_TAXONOMY_EXPORT, COLLECTION_EXPORT_WITH_CHILD, COLLECTION_EXPORT_WITHOUT_CHILD, BOOKMARK_EXPORT
}
