package com.cs.di.workflow.constants;

public enum ConfigNodeType
{
  ATTRIBUTE, TAG, CLASSIFIER, RELATIONSHIP, CONTEXT, HIERARCHY, MASTERTAXONOMY, PROPERTY_COLLECTION, USER, TASK, ARTICLE, ASSET, TEXTASSET,
  VIRTUALCATALOG, SUPPLIER, RULE, PROPERTY, GOLDENRECORDRULE, TAB, TRANSLATION, PARTNER, REFERENCE, LANGUAGE, PERMISSION;
}
