package com.cs.di.workflow.constants;


public enum ObjectCode
{
  INPUT_PARAM, MESSAGE_TYPE, ENTITY_ID, FILE_TYPE, CAMUNDA_TASK, CAMUNDA_TASK_ID, INPUT_PARAM_VALUE, SUCCESS_COUNT, TOTAL_COUNT, FAILED_COUNT,
  SUCCEEDED_IIDS, FAILED_IIDS, SERVICE;
}
