package com.cs.core.runtime.interactor.entity.propertyinstance;

import com.cs.core.runtime.interactor.entity.configuration.base.AbstractRuntimeEntity;

public class AutoGenreatedAttributeInfoInstance extends AbstractRuntimeEntity
    implements IAutoGeneratedAttributeInfoInstance {
  
  private static final long serialVersionUID = 1L;
  
  protected String          attributeId;
  protected String          klassId;
  protected String          attributeCode;
  protected String          klassCode;
  protected Integer         counter;
  protected String          suffix;
  
  @Override
  public String getAttributeId()
  {
    return attributeId;
  }
  
  @Override
  public void setAttributeId(String attributeId)
  {
    this.attributeId = attributeId;
  }
  
  @Override
  public String getKlassId()
  {
    return klassId;
  }
  
  @Override
  public void setKlassId(String klassId)
  {
    this.klassId = klassId;
  }
  
  @Override
  public String getAttributeCode()
  {
    return attributeCode;
  }
  
  @Override
  public void setAttributeCode(String attributeCode)
  {
    this.attributeCode = attributeCode;
  }
  
  @Override
  public String getKlassCode()
  {
    return klassCode;
  }
  
  @Override
  public void setKlassCode(String klassCode)
  {
    this.klassCode = klassCode;
  }
  
  @Override
  public Integer getCounter()
  {
    return counter;
  }
  
  @Override
  public void setCounter(Integer counter)
  {
    this.counter = counter;
  }
  
  @Override
  public String getSuffix()
  {
    return suffix;
  }
  
  @Override
  public void setSuffix(String suffix)
  {
    this.suffix = suffix;
  }
}
