package com.cs.core.runtime.interactor.entity.propertyinstance;

import com.cs.core.runtime.interactor.entity.configuration.base.IRuntimeEntity;

public interface IAutoGeneratedAttributeInfoInstance extends IRuntimeEntity {
  
  public static final String ATTRIBUTE_ID   = "attributeId";
  public static final String KLASS_ID       = "klassId";
  public static final String ATTRIBUTE_CODE = "attributeCode";
  public static final String KLASS_CODE     = "klassCode";
  public static final String COUNTER        = "counter";
  public static final String SUFFIX         = "suffix";
  
  public String getAttributeId();
  
  public void setAttributeId(String attributeId);
  
  public String getKlassId();
  
  public void setKlassId(String klassId);
  
  public String getAttributeCode();
  
  public void setAttributeCode(String attributeCode);
  
  public String getKlassCode();
  
  public void setKlassCode(String klassCode);
  
  public Integer getCounter();
  
  public void setCounter(Integer counter);
  
  public String getSuffix();
  
  public void setSuffix(String suffix);
}
