package com.cs.ui.config.controller.usecase.migration;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.cs.core.config.controller.usecase.config.IRuntimeController;
import com.cs.core.config.interactor.usecase.migration.IMigrationToRemoveAutoGeneratedAttributeFromDB;
import com.cs.core.runtime.interactor.model.configuration.VoidModel;
import com.cs.ui.runtime.controller.model.response.IRESTModel;
import com.cs.ui.runtime.controller.usecase.interceptor.BaseController;

@RestController
@RequestMapping(value = "/config")
public class MigrationToRemoveAutoGeneratedAttributeFromDBController extends BaseController
    implements IRuntimeController {
  
  @Autowired
  protected IMigrationToRemoveAutoGeneratedAttributeFromDB migrationToRemoveAutoGeneratedAttributeFromDB;
  
  @RequestMapping(value = "/migration/removeAutoGeneratedAttributes", method = RequestMethod.POST)
  public IRESTModel execute() throws Exception
  {
    return createResponse(migrationToRemoveAutoGeneratedAttributeFromDB.execute(new VoidModel()));
  }
}
