package com.cs.core.config.strategy.usecase.relationship;

import com.cs.core.config.strategy.configuration.base.IConfigStrategy;
import com.cs.core.runtime.interactor.entity.relationshipinstance.IConfigChangeRelationshipInheritanceModel;
import com.cs.core.runtime.interactor.entity.relationshipinstance.IGetNatureRelationshipInfoForRelationshipInheritanceResponseModel;

public interface IGetRelationshipInfoOnConfigChangeStartegy extends
IConfigStrategy<IConfigChangeRelationshipInheritanceModel, IGetNatureRelationshipInfoForRelationshipInheritanceResponseModel> {

}
