package com.cs.core.config.interactor.usecase.migration;

import com.cs.config.interactor.usecase.base.IConfigInteractor;
import com.cs.core.runtime.interactor.model.configuration.IVoidModel;

public interface IMigrationToRemoveAutoGeneratedAttributeFromDB
    extends IConfigInteractor<IVoidModel, IVoidModel> {
  
}
