package com.cs.core.config.strategy.usecase.klass;

import com.cs.core.config.interactor.model.klass.IConfigDetailsForTaxonomyTreeByLeafIdsForVariantLinkedInstancesQuicklistRequestModel;
import com.cs.core.config.interactor.model.klass.IConfigDetailsForTaxonomyTreeByLeafIdsForVariantLinkedInstancesQuicklistResponseModel;
import com.cs.core.config.strategy.configuration.base.IConfigStrategy;

public interface IConfigDetailsForTaxonomyTreeByLeafIdsForVariantLinkedInstancesQuicklistStrategy
    extends
    IConfigStrategy<IConfigDetailsForTaxonomyTreeByLeafIdsForVariantLinkedInstancesQuicklistRequestModel, IConfigDetailsForTaxonomyTreeByLeafIdsForVariantLinkedInstancesQuicklistResponseModel> {
  
}
